<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - Table sem5.dbo.INVENTORYREPORT</title>
  <link rel=stylesheet href='../schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    table='INVENTORYREPORT';
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='../index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='../relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='../constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='../anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='../columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>Table <span title='Database'>sem5</span>.<span title='Schema'>dbo</span>.<span title='Table'>INVENTORYREPORT</span></span><div style='padding: 0px 4px;'>Keeps the administrator-defined filters for the Computer Status log.</div><p>
</td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%' border='0'>
<tr valign='top'><td class='container' align='left' valign='top'>
<form name='options' action=''>
 <label for='showRelatedCols'><input type=checkbox id='showRelatedCols'>Related columns</label>
 <label for='showConstNames'><input type=checkbox id='showConstNames'>Constraints</label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
 <label for='showLegend'><input type=checkbox checked id='showLegend'>Legend</label>
</form>
</td><td class='container' rowspan='2' align='right' valign='top'>
 <table class='legend' border='0'>
  <tr>
   <td class='dataTable' valign='bottom'>Legend:</td>
  </tr>
  <tr><td class='container' colspan='2'>
   <table class='dataTable' border='1'>
    <tbody>
    <tr><td class='primaryKey'>Primary key columns</td></tr>
    <tr><td class='indexedColumn'>Columns with indexes</td></tr>
    <tr class='impliedRelationship'><td class='detail'><span class='impliedRelationship'>Implied relationships</span></td></tr>
    <tr><td class='excludedColumn'>Excluded column relationships</td></tr>
    <tr><td class='legendDetail'>&lt; <em>n</em> &gt; number of related tables</td></tr>
   </table>
  </td></tr>
 </table>
&nbsp;
</td><tr valign='top'><td class='container' align='left' valign='top'>
<a name='columns'></a>
<table id='columns' class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th>Column</th>
  <th>Type</th>
  <th>Size</th>
  <th title='Are nulls allowed?'>Nulls</th>
  <th title='Is column automatically updated?'>Auto</th>
  <th title='Default value'>Default</th>
  <th title='Columns in tables that reference this column'><span class='notSortedByColumn'>Children</span></th>
  <th title='Columns in tables that are referenced by this column'><span class='notSortedByColumn'>Parents</span></th>
  <th title='Comments' class='comment'><span class='notSortedByColumn'>Comments</span></th>
</tr>
</thead>
<tbody valign='top'>
<tr class='even'>
 <td class='detail'>INVENTORYFILTER_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='primaryKey' title='Primary Key'>USER_ID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='even'>
 <td class='primaryKey' title='Primary Key'>FILTERNAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>LASTCHECKINTIME</td>
 <td class='detail'>datetime</td>
 <td class='detail' align='right'>16,3</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('19700101')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Last time of check-in with the management server.</td>
</tr>
<tr class='even'>
 <td class='detail'>LASTSCANTIME</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Last time computer was scanned:<br />0 = Past week<br />1 = Past month <br />2 = Past three months <br />3 = Past year  <br />4 = Past 24 hours  <br />5 = Current month</td>
</tr>
<tr class='odd'>
 <td class='detail'>RELATIVEDATETYPE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('0')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Last check-in time, if relative filtering is used:<br />0 = The past week.<br />1 = The past month. <br />2 = The past three months. <br />3 = The past year. <br />4 = The past 24 hours. <br />5 = The current month.</td>
</tr>
<tr class='even'>
 <td class='detail'>OPERATOR</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used.</td>
</tr>
<tr class='odd'>
 <td class='detail'>PATTERN_IDX</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>255</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Hard-coded English string used as key (filters for Antivirus signature version):<br />WITHIN_RELATIVE_30 = Within the last 30 days<br />WITHIN_RELATIVE_90 = Within the last 90 days<br />OUTSIDE_RELATIVE_30 = Older than the last 30 days<br />OUTSIDE_RELATIVE_90 = Older than the last 90 days<br /><br />or virus definition revision which results in an < =  query on that revision.</td>
</tr>
<tr class='even'>
 <td class='detail'>PRODUCTVERSION</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Product version by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>PROFILE_VERSION</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>64</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The profile version by which to filter.</td>
</tr>
<tr class='even'>
 <td class='detail'>IDS_VERSION</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>64</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Intrusion prevention system signature version by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>GOOD</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>5</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used.</td>
</tr>
<tr class='even'>
 <td class='detail'>LICENSE_STATUS</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used.</td>
</tr>
<tr class='odd'>
 <td class='detail'>STATUS</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>1 = online, 0 = offline,127 = No filter (all).</td>
</tr>
<tr class='even'>
 <td class='detail'>ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Auto-Protect Status:<br />0 = Filter for off, 127 = No filter (all).</td>
</tr>
<tr class='odd'>
 <td class='detail'>TAMPER_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Tamper Protection status:<br />0 = Filter for off, 127 = No filter (all).</td>
</tr>
<tr class='even'>
 <td class='detail'>REBOOT_REQUIRED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Restart required status:<br />1 = Filter for needs restart, 127 = No filter (all).</td>
</tr>
<tr class='odd'>
 <td class='detail'>AVENGINE_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Antivirus Engine Status:<br />0 = Filter for off, 127 = No filter (all).</td>
</tr>
<tr class='even'>
 <td class='detail'>TPM_DEVICE</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>TPM device installed:<br />1 = Filters on device is installed, 127 = No filter (all).</td>
</tr>
<tr class='odd'>
 <td class='detail'>SERVERGROUPLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-carded list of domain names by which to filter.</td>
</tr>
<tr class='even'>
 <td class='detail'>CLIENTGROUPLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-carded list of group names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>PARENTSERVERLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-carded list of server names by which to filter.</td>
</tr>
<tr class='even'>
 <td class='detail'>SITELIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-carded list of site names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>R_OS_TYPE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>600 = Windows Vista and Windows Server 2008,<br />502 = Windows 2003 and Windows XP 64 bit,<br />501 = Windows XP,<br />500 = Windows 2000,<br />400 = Windows NT<br />000 = Other<br />-1 = No filter (all).</td>
</tr>
<tr class='even'>
 <td class='detail'>HI_STATUS</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Filters on the following compliance status:<br />0 = Fail<br />1 = Success<br />2 = Pending<br />3 = Disabled<br />4 = Ignore<br />127 = No filter (all).</td>
</tr>
<tr class='odd'>
 <td class='detail'>HI_REASONCODE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Filters on the following reasons:<br />0 = Pass<br />101 = Antivirus version is out-of-date<br />102 = Antivirus is not running<br />103 = Script failed<br />104 = Check is incomplete<br />105 = Check is disabled<br />127 = Location changed<br />-1 = No filter (all).</td>
</tr>
<tr class='even'>
 <td class='detail'>SERVICE_PACK</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>128</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>OS service pack, or % for no filter (all).</td>
</tr>
<tr class='odd'>
 <td class='detail'>WORSTINFECTION_IDX</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used.</td>
</tr>
<tr class='even'>
 <td class='detail'>COMPUTERLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>1024</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-carded list of computer names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>IPADDRESSLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The comma-separated, wild-carded list of IP addresses by which to filter.</td>
</tr>
<tr class='even'>
 <td class='detail'>USERLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-carded list of user names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>INFECTED</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>2</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>'On' indicates the computer is infected.</td>
</tr>
<tr class='even'>
 <td class='detail'>SORTORDER</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('LAST_UPDATE_TIME')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The column by which to sort, for the Computer Status log.</td>
</tr>
<tr class='odd'>
 <td class='detail'>SORTDIR</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>5</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('DESC')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Sort order. Ascending or descending.</td>
</tr>
<tr class='even'>
 <td class='detail'>FILVIEW</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>16</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('SAVCE')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used.</td>
</tr>
<tr class='odd'>
 <td class='detail'>CLIENTTYPE</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used.</td>
</tr>
<tr class='even'>
 <td class='detail'>LIMITROWS</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('20')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The number of rows to use for pagination.</td>
</tr>
<tr class='odd'>
 <td class='detail'>USERELATIVE</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>2</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('on')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Use relative dates ('on'), or absolute dates.</td>
</tr>
<tr class='even'>
 <td class='detail'>REPORT_IDX</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('0')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used.</td>
</tr>
<tr class='odd'>
 <td class='detail'>REPORTINPUTS</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>128</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Special parameters, if the report needs them.</td>
</tr>
<tr class='even'>
 <td class='detail'>USN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>A USN-based serial number; this ID is not unique.</td>
</tr>
<tr class='odd'>
 <td class='detail'>TIME_STAMP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time on the server when the event is logged into the system (GMT).</td>
</tr>
<tr class='even'>
 <td class='detail'>DELETED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Deleted row: 0 = Not deleted, 1 = Deleted.</td>
</tr>
<tr class='odd'>
 <td class='detail'>FIREWALL_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Firewall status:<br />0 = Filters on / off, 127 = No filter (all).</td>
</tr>
<tr class='even'>
 <td class='detail'>DA_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Download advisor status<br />Enabled state of DA<br />0 = off<br />1 = on<br /> 2 = not installed<br />3 = off by admin policy<br />127 = unknown.</td>
</tr>
<tr class='odd'>
 <td class='detail'>PTP_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Proactive threat protection status:<br />0 = Off<br />1 = On<br /> 2 = Not installed<br />3 = Off by administrator policy<br />127 = Unknown <br />The default is 127.</td>
</tr>
<tr class='even'>
 <td class='detail'>CIDS_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Network intrusion prevention status:<br />0 = Off<br />1 = On<br /> 2 = Not installed<br />3 = Off by administrator policy<br />127 = Unknown. <br />Default is 127.</td>
</tr>
<tr class='odd'>
 <td class='detail'>DEPLOY_STATUS</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>See SEM_AGENT.DEPLOY_STATUS.  Included again in this table because it represents a filter option.</td>
</tr>
<tr class='even'>
 <td class='detail'>CIDS_BROWSER_IE_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>See SEM_AGENT.CIDS_BROWSER_IE_ONOFF.  Included again in this table because it represents a filter option.</td>
</tr>
<tr class='odd'>
 <td class='detail'>CIDS_BROWSER_FF_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>See SEM_AGENT.CIDS_BROWSER_FF_ONOFF.  Included again in this table because it represents a filter option.</td>
</tr>
<tr class='even'>
 <td class='detail'>ELAM_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Early Launch Anti-Malware status:<br />0 = Off<br />1 = On<br /> 2 = Not installed<br />3 = Off by administrator policy<br />127 = Unknown. <br />Default is 127.</td>
</tr>
<tr class='odd'>
 <td class='detail'>PEP_ONOFF</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((127))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Generic Exploit Mitigation status:<br />0 = Off<br />1 = On<br /> 2 = Not installed<br />3 = Off by administrator policy<br />127 = Unknown. <br />Default is 127.</td>
</tr>
</table>
<p title='52 columns'>Analyzed at Wed Apr 12 14:15 PDT 2017<p/>
</td></tr></table>
<div class='indent'>
<b>Indexes:</b>
<table class='dataTable' border='1' rules='groups'><colgroup><colgroup><colgroup><colgroup>
<thead>
 <tr>
  <th>Column(s)</th>
  <th>Type</th>
  <th>Sort</th>
  <th class='constraint' style='text-align:left;'>Constraint Name</th>
 </tr>
</thead>
<tbody>
 <tr>
  <td class='primaryKey'>USER_ID + FILTERNAME</td>
  <td class='detail'>Primary key</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>PK_INVENTORYREPORT</td>
 </tr>
</table>
</div>
</div>
</body>
</html>
