<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - Table sem5.dbo.NOTIFICATION</title>
  <link rel=stylesheet href='../schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    table='NOTIFICATION';
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='../index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='../relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='../constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='../anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='../columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>Table <span title='Database'>sem5</span>.<span title='Schema'>dbo</span>.<span title='Table'>NOTIFICATION</span></span><div style='padding: 0px 4px;'>Keeps the notification events.</div><p>
</td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%' border='0'>
<tr valign='top'><td class='container' align='left' valign='top'>
<form name='options' action=''>
 <label for='showRelatedCols'><input type=checkbox id='showRelatedCols'>Related columns</label>
 <label for='showConstNames'><input type=checkbox id='showConstNames'>Constraints</label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
 <label for='showLegend'><input type=checkbox checked id='showLegend'>Legend</label>
</form>
</td><td class='container' rowspan='2' align='right' valign='top'>
 <table class='legend' border='0'>
  <tr>
   <td class='dataTable' valign='bottom'>Legend:</td>
  </tr>
  <tr><td class='container' colspan='2'>
   <table class='dataTable' border='1'>
    <tbody>
    <tr><td class='primaryKey'>Primary key columns</td></tr>
    <tr><td class='indexedColumn'>Columns with indexes</td></tr>
    <tr class='impliedRelationship'><td class='detail'><span class='impliedRelationship'>Implied relationships</span></td></tr>
    <tr><td class='excludedColumn'>Excluded column relationships</td></tr>
    <tr><td class='legendDetail'>&lt; <em>n</em> &gt; number of related tables</td></tr>
   </table>
  </td></tr>
 </table>
&nbsp;
</td><tr valign='top'><td class='container' align='left' valign='top'>
<a name='columns'></a>
<table id='columns' class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th>Column</th>
  <th>Type</th>
  <th>Size</th>
  <th title='Are nulls allowed?'>Nulls</th>
  <th title='Is column automatically updated?'>Auto</th>
  <th title='Default value'>Default</th>
  <th title='Columns in tables that reference this column'><span class='notSortedByColumn'>Children</span></th>
  <th title='Columns in tables that are referenced by this column'><span class='notSortedByColumn'>Parents</span></th>
  <th title='Comments' class='comment'><span class='notSortedByColumn'>Comments</span></th>
</tr>
</thead>
<tbody valign='top'>
<tr class='even'>
 <td class='primaryKey' title='Primary Key'>NOTAG_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>TYPE</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>30</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>VO = Risk outbreak<br />SO = Outbreak on single computers<br />VM = Outbreak by number of computers<br />1V = Single risk event<br />NV = New risk detected<br />ID = Virus definitions out-of-date<br />AF = Authentication failure<br />AFS = Authentication failure on single server<br />SE = System event<br />CS = Client security alert<br />CSS = Client security alert on single computers<br />CSM = Client security alert by number of computers<br />LA = New learned application<br />CL = Client list changed<br />DF = Server health<br />UM = Unmanaged computers<br />NS = New software package<br />ED = Enforcer is down<br />WL = Forced or Commercial application detected<br />DD = Database down<br />LE = Paid license expiring<br />TLE = Trial license expiring<br />ODC = SEPM is overdeployed with the current license<br />OLE = Upgrade license expiring</td>
</tr>
<tr class='even'>
 <td class='detail'>USER_ID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The administrator's GUID.</td>
</tr>
<tr class='odd'>
 <td class='detail'>TZ_OFFSET</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time zone offset from when the administrator created the notification, so that the dates in the notification are formatted for the administrator's local time zone.</td>
</tr>
<tr class='even'>
 <td class='detail'>SERVERGROUP</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The name of the server group(s) to which this notification applies. Comma-separated list, wild-cards allowed.</td>
</tr>
<tr class='odd'>
 <td class='detail'>CLIENTGROUP</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The name of the client group(s) to which this notification applies. Comma-separated list, wild-cards allowed.</td>
</tr>
<tr class='even'>
 <td class='detail'>PARENTSERVER</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Name of management server(s) to which this notification applies. Comma-separated list, wild-cards allowed.</td>
</tr>
<tr class='odd'>
 <td class='detail'>COMPUTER</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The name of the computer(s) to which this notification applies (comma-separated list, wild-cards allowed).</td>
</tr>
<tr class='even'>
 <td class='detail'>VIRUS</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The name of the threat(s) to which this notification applies. Comma-separated list, wild-cards allowed.</td>
</tr>
<tr class='odd'>
 <td class='detail'>SOURCE</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>255</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Scan for which this notification applies (hard-coded English string used as key):<br />% = all<br />Scheduled Scan<br />Manual Scan<br />Real-Time Scan<br />Heuristic Scan<br />Console<br />Definition downloader<br />System<br />Startup Scan<br />Idle Scan<br />Manual Quarantine</td>
</tr>
<tr class='even'>
 <td class='detail'>ACTACTION</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>255</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('%')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>% = No filter (all)<br />1 = Quarantined<br />3 = Deleted<br />4 = Left alone<br />5 = Cleaned<br />6 = Cleaned or macros deleted<br />14 = Pending repair<br />15 = Partially repaired<br />16 = Process termination pending restart<br />17 = Excluded<br />19 = Cleaned by deletion<br />20 = Access denied<br />21 = Process terminated<br />22 = No repair available<br />23 = All actions failed<br />98 = Suspicious<br /></td>
</tr>
<tr class='odd'>
 <td class='detail'>HYPERLINK2</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('/reports/FullReport.php')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The hyperlink used to generate the report.</td>
</tr>
<tr class='even'>
 <td class='detail'>NTIMES</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The number of occurrences required to trigger this notification.</td>
</tr>
<tr class='odd'>
 <td class='detail'>XMINUTES</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The window of time in which the specified number of events must occur in order to trigger the notification.</td>
</tr>
<tr class='even'>
 <td class='detail'>EMAIL</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The comma-separated list of email addresses to which an email is sent when this notification is triggered.</td>
</tr>
<tr class='odd'>
 <td class='detail'>LASTRUN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time stamp for when this notification was last generated.</td>
</tr>
<tr class='even'>
 <td class='detail'>TRIGGERED</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time when the alert last triggered.</td>
</tr>
<tr class='odd'>
 <td class='detail'>LASTRUN_DATA</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>50</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Any extra data that is needed to provide details in the notification email.</td>
</tr>
<tr class='even'>
 <td class='detail'>CATEGORY</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>10</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('>= -1')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Virus category for which this notification applies:<br />>= -1 is no filter (all) <br />>= 1 filters for Category 1 (Very Low) and above<br />>= 2 filters for Category 2 (Low) and above<br />>= 3 filters for Category 3 (Moderate) and above<br />>= 4 filters for Category 4 (Severe) and above<br />>= 5 filters for Category 5 (Very Severe)<br /> = -1 filters for unknown</td>
</tr>
<tr class='odd'>
 <td class='detail'>USN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>A USN-based serial number; this ID is not unique.</td>
</tr>
<tr class='even'>
 <td class='detail'>TIME_STAMP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time on the server when the event is logged into the system (GMT).</td>
</tr>
<tr class='odd'>
 <td class='detail'>DELETED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Deleted row: 0 = Not deleted, 1 = Deleted.</td>
</tr>
<tr class='even'>
 <td class='detail'>SYSTEM_EVENT</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Which buckets of system events</td>
</tr>
<tr class='odd'>
 <td class='detail'>SECURITY_EVENT</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Which buckets of security events</td>
</tr>
<tr class='even'>
 <td class='detail'>DAMPER</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The minimum quiet time between alerts, in minutes; 0 means autodamper, which is 60 minutes.</td>
</tr>
<tr class='odd'>
 <td class='detail'>BATCH_FILE_NAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>128</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The batch file or executable to execute when the notification triggers.</td>
</tr>
<tr class='even'>
 <td class='detail'>NAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The name of the notification configuration.</td>
</tr>
<tr class='odd'>
 <td class='detail'>IS_MAIL_TO_SYS_ADMIN</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('1')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The flag for mailing to the System Administrator.</td>
</tr>
<tr class='even'>
 <td class='detail'>CLIENTPACKAGE_TYPE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('0')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The client package type.</td>
</tr>
<tr class='odd'>
 <td class='detail'>TZ_NAME</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>255</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The name of the time zone in which the administrator created the notification, so that emailed reports can display dates in the administrator's local time zone.</td>
</tr>
<tr class='even'>
 <td class='detail'>CLIENT_TRIGGERED</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time when the notification condition was last triggered. As of version 12.1.2, this column is used instead of TRIGGERED.</td>
</tr>
<tr class='odd'>
 <td class='detail'>EMAILSUBJECT</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
</table>
<p title='32 columns'>Analyzed at Wed Apr 12 14:15 PDT 2017<p/>
</td></tr></table>
<div class='indent'>
<b>Indexes:</b>
<table class='dataTable' border='1' rules='groups'><colgroup><colgroup><colgroup><colgroup>
<thead>
 <tr>
  <th>Column(s)</th>
  <th>Type</th>
  <th>Sort</th>
  <th class='constraint' style='text-align:left;'>Constraint Name</th>
 </tr>
</thead>
<tbody>
 <tr>
  <td class='primaryKey'>NOTAG_IDX</td>
  <td class='detail'>Primary key</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>PK_NOTIFICATION</td>
 </tr>
</table>
</div>
</div>
</body>
</html>
