<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - sem5.dbo - Constraints</title>
  <link rel=stylesheet href='schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='schemaSpy.js'></SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li id='current'><a href='constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>SchemaSpy Analysis of <span title='Database'>sem5</span>.<span title='Schema'>dbo</span> - Constraints</span><span class='description'>Symantec Endpoint Protection Manager Database Schema</span></td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<div class='indent'>
<table width='100%'>
<tr><td class='container' valign='bottom'><b>
0 Foreign Key Constraints:</b>
</td><td class='container' align='right'>
<table>
<tr><td class='container'>
</td></tr></table>
</td></tr>
</table><br>
<table class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<thead align='left'>
<tr>
  <th>Constraint Name</th>
  <th>Child Column</th>
  <th>Parent Column</th>
  <th>Delete Rule</th>
</tr>
</thead>
<tbody>
 <tr>
  <td class='detail' valign='top' colspan='4'>None detected</td>
 </tr>
</tbody>
</table>
<a name='checkConstraints'></a><p>
<b>Check Constraints:</b>
<TABLE class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<thead align='left'>
<tr>
  <th>Table</th>
  <th>Constraint Name</th>
  <th>Constraint</th>
</tr>
</thead>
<tbody>
 <tr>
  <td class='detail' valign='top' colspan='3'>None detected</td>
 </tr>
</tbody>
</table>
</div>
</div>
</body>
</html>
