<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - sem5.dbo</title>
  <link rel=stylesheet href='schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    $(function(){
      associate($('#showTables'), $('.tbl'));
      associate($('#showViews'),  $('.view'));
      jQuery.fn.alternateRowColors = function() {
        $('tbody tr:visible').each(function(i) {
          if (i % 2 == 0) {
            $(this).removeClass('even').addClass('odd');
          } else {
            $(this).removeClass('odd').addClass('even');
          }
        });
        return this;
      };
      $('#showTables, #showViews').click(function() {
        $('table.dataTable').alternateRowColors();
      });
      $('table.dataTable').alternateRowColors();
    })
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li id='current'><a href='index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>SchemaSpy Analysis of <span title='Database'>sem5</span>.<span title='Schema'>dbo</span></span><span class='description'>Symantec Endpoint Protection Manager Database Schema</span></td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%'>
 <tr><td class='container'>
<span class='container'>Generated by <span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span> on Wed Apr 12 14:15 PDT 2017</span>
 </td></tr>
 <tr>
  <td class='container'>Database Type: Microsoft SQL Server - 11.00.2100  </td>
  <td class='container' align='right' valign='top' rowspan='3'>
    <br>  </td>
 </tr>
 <tr>
  <td class='container'><br><a href='sem5.dbo.xml' title='XML Representation'>XML Representation</a><br><a href='insertionOrder.txt' title='Useful for loading data into a database'>Insertion Order</a>&nbsp;<a href='deletionOrder.txt' title='Useful for purging data from a database'>Deletion Order</a>&nbsp;(for database loading/purging scripts)</td>
 </tr>
</table>
<div class='indent'>
<p><b><label for='showTables' style='display:none;'><input type='checkbox' id='showTables' checked></label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
</b>
<table class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th valign='bottom'>Table</th>
  <th align='right' valign='bottom'>Children</th>
  <th align='right' valign='bottom'>Parents</th>
  <th align='right' valign='bottom'>Columns</th>
  <th class='comment' align='left' valign='bottom'>Comments</th>
</tr>
</thead>
<tbody>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ACTUALACTION.html'>ACTUALACTION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>2</td>
  <td class='comment detail'>Lists and defines the meanings of the antivirus remediation action integers.  The action integers represent the actions that the antivirus engine can take when dealing with a threat.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ADMIN_GROUP_REFRESH_INFO.html'>ADMIN_GROUP_REFRESH_INFO</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>3</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ADMIN_GROUPS.html'>ADMIN_GROUPS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>3</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ADMINUSER.html'>ADMINUSER</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>6</td>
  <td class='comment detail'>A list of reporting administrators.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_BEHAVIOR_LOG_1.html'>AGENT_BEHAVIOR_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>45</td>
  <td class='comment detail'>Keeps client activities that occur in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_BEHAVIOR_LOG_2.html'>AGENT_BEHAVIOR_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>45</td>
  <td class='comment detail'>Keeps client activities that occur in agents. The LOG_IDX field serves as the table's unique identifier, but it is not formally classified as the table's primary key. This field has an index on it, but it is not the primary key index. This table has no primary key.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_DEF_CACHE.html'>AGENT_DEF_CACHE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Used to cache the current definition numbers used by agents for reporting.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_PACKET_LOG_1.html'>AGENT_PACKET_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>35</td>
  <td class='comment detail'>Keeps packet traffic that occurs in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_PACKET_LOG_2.html'>AGENT_PACKET_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>35</td>
  <td class='comment detail'>Keeps packet traffic that occur in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_SECURITY_LOG_1.html'>AGENT_SECURITY_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>54</td>
  <td class='comment detail'>Keeps security events that occur in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_SECURITY_LOG_2.html'>AGENT_SECURITY_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>54</td>
  <td class='comment detail'>Keeps security events that occur in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_SYSTEM_LOG_1.html'>AGENT_SYSTEM_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>27</td>
  <td class='comment detail'>Keeps system traffic that occur in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_SYSTEM_LOG_2.html'>AGENT_SYSTEM_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>27</td>
  <td class='comment detail'>Keeps system traffic that occur in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_TRAFFIC_LOG_1.html'>AGENT_TRAFFIC_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>47</td>
  <td class='comment detail'>Keeps network traffic that occur in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENT_TRAFFIC_LOG_2.html'>AGENT_TRAFFIC_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>47</td>
  <td class='comment detail'>Keeps network traffic that occur in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENTCONFIG.html'>AGENTCONFIG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Not used.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AGENTSTATUS.html'>AGENTSTATUS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>11</td>
  <td class='comment detail'>The status of SEPM server tasks.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ALERTFILTER.html'>ALERTFILTER</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>25</td>
  <td class='comment detail'>The administrator-defined filters for the notification log.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ALERTMSG.html'>ALERTMSG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>2</td>
  <td class='comment detail'>Lists and defines the meanings of the events possible for the Risk and Proactive Threat Protection (TruScan) log.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ALERTS.html'>ALERTS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>34</td>
  <td class='comment detail'>Keeps the risk and Proactive Threat Protection (TruScan) events.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ANOMALYDETECTION.html'>ANOMALYDETECTION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>8</td>
  <td class='comment detail'>Keeps the antivirus detection events.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ANOMALYDETECTIONOPERATION.html'>ANOMALYDETECTIONOPERATION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>2</td>
  <td class='comment detail'>Lists and defines what a detection can possibly find.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ANOMALYDETECTIONS.html'>ANOMALYDETECTIONS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>8</td>
  <td class='comment detail'>Keeps the client to detection event mappings.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ANOMALYDETECTIONTYPE.html'>ANOMALYDETECTIONTYPE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>2</td>
  <td class='comment detail'>Lists and defines the kinds of objects that detections work on.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ANOMALYREMEDIATION.html'>ANOMALYREMEDIATION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>8</td>
  <td class='comment detail'>Keeps the antivirus remediation events.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ANOMALYREMEDIATIONOPERATION.html'>ANOMALYREMEDIATIONOPERATION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>2</td>
  <td class='comment detail'>Lists and defines what a remediation can possibly do.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ANOMALYREMEDIATIONS.html'>ANOMALYREMEDIATIONS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>8</td>
  <td class='comment detail'>Keeps the client-to-remediation event mappings.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ANOMALYREMEDIATIONTYPE.html'>ANOMALYREMEDIATIONTYPE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>2</td>
  <td class='comment detail'>Lists and defines the kinds of objects that remediations work on.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AUDIT_LOG.html'>AUDIT_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>6</td>
  <td class='comment detail'>Keeps an audit trail for every action performed by a SEPM user, and when.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/AUDIT_REPORT.html'>AUDIT_REPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>21</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the Audit log.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/BASIC_METADATA.html'>BASIC_METADATA</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>22</td>
  <td class='comment detail'>Keeps policy and various server settings.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/BEHAVIOR_REPORT.html'>BEHAVIOR_REPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>30</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the Application Control log.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/BINARY_FILE.html'>BINARY_FILE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>17</td>
  <td class='comment detail'>Keeps all binary files.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/CLIENT_GROUPS_CACHE.html'>CLIENT_GROUPS_CACHE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>9</td>
  <td class='comment detail'>The flattened relational cache of the parent-child group hierarchy.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/CLIENT_GROUPS_CACHE_INFO.html'>CLIENT_GROUPS_CACHE_INFO</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>4</td>
  <td class='comment detail'>Keeps track of when the cache data refreshes.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/CLIENT_GROUPS_CACHE_STAGING.html'>CLIENT_GROUPS_CACHE_STAGING</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>8</td>
  <td class='comment detail'>Temporarily stores the result of the client group tree during flattening.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/COMMAND.html'>COMMAND</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>23</td>
  <td class='comment detail'>Keeps the Command status for agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/COMMAND_REPORT.html'>COMMAND_REPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>19</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the Command details log.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/COMPLIANCE_REPORT.html'>COMPLIANCE_REPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>41</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the Device Control log, the NTP Attacks log, and all the Compliance logs.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/COMPUTER_APPLICATION.html'>COMPUTER_APPLICATION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>21</td>
  <td class='comment detail'>Keeps all applications used in agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/CONNECTION_TEST.html'>CONNECTION_TEST</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>1</td>
  <td class='comment detail'>For internal use. Indicates the state of the database connection.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/CONTENT_EVENTS.html'>CONTENT_EVENTS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>19</td>
  <td class='comment detail'>Contains all event records when a client content request results in a full content distribution.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/DATA_HANDLER.html'>DATA_HANDLER</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Keeps the list of registered log handlers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/DATE_DIMENSION.html'>DATE_DIMENSION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>23</td>
  <td class='comment detail'>Holds date dimension information. This table has no primary key.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/DUMMY.html'>DUMMY</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>0</td>
  <td class='comment detail'>Dummy table for internal use.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ENFORCER_CLIENT_LOG_1.html'>ENFORCER_CLIENT_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>30</td>
  <td class='comment detail'>Keeps client activities that occur in Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ENFORCER_CLIENT_LOG_2.html'>ENFORCER_CLIENT_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>30</td>
  <td class='comment detail'>Keeps client activities that occur in Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ENFORCER_SYSTEM_LOG_1.html'>ENFORCER_SYSTEM_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'>Keeps client system activities that occur in Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ENFORCER_SYSTEM_LOG_2.html'>ENFORCER_SYSTEM_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'>Keeps client system activities that occur in Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ENFORCER_TRAFFIC_LOG_1.html'>ENFORCER_TRAFFIC_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>30</td>
  <td class='comment detail'>Keeps client traffic activities that occur in Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ENFORCER_TRAFFIC_LOG_2.html'>ENFORCER_TRAFFIC_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>30</td>
  <td class='comment detail'>Keeps client traffic activities that occur in Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ENROLMENT_JOB_STATUS.html'>ENROLMENT_JOB_STATUS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Holds submitted enrollment job-related statuses for bulk updating device information in batches. Enroll job updates 'Hardware Key', 'Device Id', 'Public Key', 'Device Info' to help enabling communication between ATP, SEPM, SEP (EDR).</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/ENUM_MAP.html'>ENUM_MAP</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>3</td>
  <td class='comment detail'>For internal use only. Supports the automation of internal processes.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/FIREWALL_REPORT.html'>FIREWALL_REPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>33</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the NTP Traffic and Packet logs.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/GROUP_HI_STATUS.html'>GROUP_HI_STATUS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>3</td>
  <td class='comment detail'>Specify if the Host Integrity feature is enabled or not.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/GROUP_LAN_SENSOR.html'>GROUP_LAN_SENSOR</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>4</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/GUIPARMS.html'>GUIPARMS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>6</td>
  <td class='comment detail'>Keeps parameters used in the console GUI.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/GUP_LIST.html'>GUP_LIST</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Keeps the list for Group Update Provider (GUP).</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/HISTORY.html'>HISTORY</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>6</td>
  <td class='comment detail'>Keeps data snapshots used in reporting</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/HISTORYCONFIG.html'>HISTORYCONFIG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>20</td>
  <td class='comment detail'>Keeps scheduled report configuration information</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/HOMEPAGECONFIG.html'>HOMEPAGECONFIG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Keeps administrator-specific preferences.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/HPP_ALERTS.html'>HPP_ALERTS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>19</td>
  <td class='comment detail'>Keeps Proactive Threat Protection (TruScan) event information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/HPP_APPLICATION.html'>HPP_APPLICATION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>14</td>
  <td class='comment detail'>Keeps applications detected by TruScan.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/HYPERVISOR_PATTERN.html'>HYPERVISOR_PATTERN</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>4</td>
  <td class='comment detail'>Keeps the information to identify virtual platform vendors.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/HYPERVISOR_VENDOR.html'>HYPERVISOR_VENDOR</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>2</td>
  <td class='comment detail'>Keeps virtual platform vendors names.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/IDENTITY_MAP.html'>IDENTITY_MAP</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>14</td>
  <td class='comment detail'>Keeps the mapping of the object ID and its name.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/INVENTORYCURRENTRISK.html'>INVENTORYCURRENTRISK</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>0</td>
  <td class='comment detail'>Keeps the client to infected threat events mapping</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/INVENTORYCURRENTRISK1.html'>INVENTORYCURRENTRISK1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>13</td>
  <td class='comment detail'>Keeps the client to infected threat events mapping</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/INVENTORYCURRENTVIRUS.html'>INVENTORYCURRENTVIRUS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>0</td>
  <td class='comment detail'>Keeps the client to infected virus events mapping.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/INVENTORYREPORT.html'>INVENTORYREPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>52</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the Computer Status log.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/LAN_DEVICE_DETECTED.html'>LAN_DEVICE_DETECTED</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>20</td>
  <td class='comment detail'>Keeps LAN devices info detected by LAN sensors.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/LAN_DEVICE_EXCLUDED.html'>LAN_DEVICE_EXCLUDED</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>19</td>
  <td class='comment detail'>Keeps known LAN device info.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/LEGACY_AGENT.html'>LEGACY_AGENT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'>Keeps legacy agent information</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/LICENSE.html'>LICENSE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>22</td>
  <td class='comment detail'>Keeps the license information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/LICENSE_CHAIN.html'>LICENSE_CHAIN</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>11</td>
  <td class='comment detail'>Keeps the license chain information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/LOCAL_METADATA.html'>LOCAL_METADATA</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>13</td>
  <td class='comment detail'>Keeps various local settings.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/LOG_CONFIG.html'>LOG_CONFIG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>15</td>
  <td class='comment detail'>Keeps logs settings for switching log tables.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/NETWORK_SCAN.html'>NETWORK_SCAN</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>0</td>
  <td class='comment detail'>Keeps temporary data for network scan.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/NETWORK_SCAN_RESULT.html'>NETWORK_SCAN_RESULT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>0</td>
  <td class='comment detail'>Keeps temporary result data for network scan.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/NOTIFICATION.html'>NOTIFICATION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>32</td>
  <td class='comment detail'>Keeps the notification events.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/NOTIFICATIONALERTS.html'>NOTIFICATIONALERTS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>13</td>
  <td class='comment detail'>Keeps the notification conditions.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/NOTIFICATIONHISTORY.html'>NOTIFICATIONHISTORY</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>6</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/OAUTH_ACCESS_TOKEN.html'>OAUTH_ACCESS_TOKEN</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>9</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/OAUTH_CLIENT_DETAILS.html'>OAUTH_CLIENT_DETAILS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/OAUTH_REFRESH_TOKEN.html'>OAUTH_REFRESH_TOKEN</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/OAUTH_TRUSTED_PARTNER.html'>OAUTH_TRUSTED_PARTNER</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>3</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/PATTERN.html'>PATTERN</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>11</td>
  <td class='comment detail'>Keeps the content versions that the clients are using.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/PROCESS_STATE.html'>PROCESS_STATE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>5</td>
  <td class='comment detail'>Tracks whether Symantec Endpoint Protection Manager processes are locked or unlocked.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/PROCESSING_MARKER.html'>PROCESSING_MARKER</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>10</td>
  <td class='comment detail'>For internal use only. Used for batch processing.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/REPORTS.html'>REPORTS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'>Not used.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SCANREPORT.html'>SCANREPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>30</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the Scan log.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SCANS.html'>SCANS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>24</td>
  <td class='comment detail'>Keeps the antivirus scan events.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SCFINVENTORY.html'>SCFINVENTORY</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>8</td>
  <td class='comment detail'>Not used.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SE_GLOBAL.html'>SE_GLOBAL</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>1</td>
  <td class='comment detail'>Keeps system sequence number.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_AGENT.html'>SEM_AGENT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>93</td>
  <td class='comment detail'>Keeps agent information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_AGENT_INFECTION_HISTORY.html'>SEM_AGENT_INFECTION_HISTORY</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Holds the infection history for an agent. This table has no primary key.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_APPLICATION.html'>SEM_APPLICATION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>26</td>
  <td class='comment detail'>Keeps all applications' information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_CLIENT.html'>SEM_CLIENT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>30</td>
  <td class='comment detail'>Keeps clients' information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_COMPLIANCE_CRITERIA.html'>SEM_COMPLIANCE_CRITERIA</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>13</td>
  <td class='comment detail'>Keeps the host compliance event details.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_COMPLIANCE_CRITERIA_2.html'>SEM_COMPLIANCE_CRITERIA_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>13</td>
  <td class='comment detail'>Keeps the host compliance event details.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_COMPUTER.html'>SEM_COMPUTER</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>64</td>
  <td class='comment detail'>Keeps computers' information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_CONTENT.html'>SEM_CONTENT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Keeps the client-to-content mapping.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_JOB.html'>SEM_JOB</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>19</td>
  <td class='comment detail'>Keeps job name for Command process.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_OS_INFO.html'>SEM_OS_INFO</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>13</td>
  <td class='comment detail'>Maps the operating system text to its version and flavor.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_REPLICATION_STATE.html'>SEM_REPLICATION_STATE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>5</td>
  <td class='comment detail'>Keeps the replication site and server information for USN generation.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_SVA.html'>SEM_SVA</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>34</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_SVA_CLIENT.html'>SEM_SVA_CLIENT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>26</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SEM_SVA_COMPUTER.html'>SEM_SVA_COMPUTER</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>51</td>
  <td class='comment detail'></td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERIAL_NUMBERS.html'>SERIAL_NUMBERS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>4</td>
  <td class='comment detail'>Stores group ID and profile serial numbers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_ADMIN_LOG_1.html'>SERVER_ADMIN_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>21</td>
  <td class='comment detail'>Keeps administrator activities that occur in server</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_ADMIN_LOG_2.html'>SERVER_ADMIN_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>21</td>
  <td class='comment detail'>Keeps administrator activities that occur in server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_CLIENT_LOG_1.html'>SERVER_CLIENT_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>20</td>
  <td class='comment detail'>Keeps client activities that occur in server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_CLIENT_LOG_2.html'>SERVER_CLIENT_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>20</td>
  <td class='comment detail'>Keeps client activities that occur in server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_ENFORCER_LOG_1.html'>SERVER_ENFORCER_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>15</td>
  <td class='comment detail'>Keeps Enforcer activities that occur on the server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_ENFORCER_LOG_2.html'>SERVER_ENFORCER_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>15</td>
  <td class='comment detail'>Keeps Enforcer activities that occur on the server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_POLICY_LOG_1.html'>SERVER_POLICY_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'>Keeps policy change activities that occur in server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_POLICY_LOG_2.html'>SERVER_POLICY_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'>Keeps policy change activities that occur in server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_SYSTEM_LOG_1.html'>SERVER_SYSTEM_LOG_1</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>19</td>
  <td class='comment detail'>Keeps system activities that occur in server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SERVER_SYSTEM_LOG_2.html'>SERVER_SYSTEM_LOG_2</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>19</td>
  <td class='comment detail'>Keeps system activities that occur in server.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SYSTEM_REPORT.html'>SYSTEM_REPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>31</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the System logs.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/SYSTEM_STATE.html'>SYSTEM_STATE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>17</td>
  <td class='comment detail'>Keeps administrator and site health status information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/TASKSTATE.html'>TASKSTATE</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>8</td>
  <td class='comment detail'>For internal use only. Indicates whether a given process is still running or is hanging.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/THREATREPORT.html'>THREATREPORT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>47</td>
  <td class='comment detail'>Keeps the administrator-defined filters for the Risk and TruScan logs.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/TIME_OF_DAY.html'>TIME_OF_DAY</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>1</td>
  <td class='comment detail'>Holds hours of a day. This table has no primary key.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/UPGRADE_CONTENT_LOOKUP.html'>UPGRADE_CONTENT_LOOKUP</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>5</td>
  <td class='comment detail'>Provides any newly introduced contents or if newer version of contents are available. This table has no primary key. <br />1. With newer release of SEP, consider that AV_DEFS changes, so while inserting a row with new moniker value, the CONTENT_TYPE should be strictly AV_DEFS, so that we can get latest moniker for AV_DEFS when re run the query on them. <br /> 2. With newer release of SEP, if new content is introduced say ABC, then identify a proper CONTENT_TYPE for it, which should be different from available values in CONTENT_TYPE.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_AGENT_BEHAVIOR_LOG.html'>V_AGENT_BEHAVIOR_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>46</td>
  <td class='comment detail'>Query the client activities for agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_AGENT_PACKET_LOG.html'>V_AGENT_PACKET_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>37</td>
  <td class='comment detail'>Query the packet traffic events for agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_AGENT_SECURITY_LOG.html'>V_AGENT_SECURITY_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>56</td>
  <td class='comment detail'>Query the security events for agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_AGENT_SYSTEM_LOG.html'>V_AGENT_SYSTEM_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>27</td>
  <td class='comment detail'>Query the system events for agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_AGENT_TRAFFIC_LOG.html'>V_AGENT_TRAFFIC_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>49</td>
  <td class='comment detail'>Query the traffic events for agents.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_ALERTS.html'>V_ALERTS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>35</td>
  <td class='comment detail'>Query the risk and TruScan events with human-readable IP address information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_CLIENT_CHANGE_LOG.html'>V_CLIENT_CHANGE_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>13</td>
  <td class='comment detail'>Query the client change events.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_DOMAINS.html'>V_DOMAINS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>14</td>
  <td class='comment detail'>Query the domain information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_ENFORCER_CLIENT_LOG.html'>V_ENFORCER_CLIENT_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>30</td>
  <td class='comment detail'>Query the client activities for Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_ENFORCER_SYSTEM_LOG.html'>V_ENFORCER_SYSTEM_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'>Query the system activities for Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_ENFORCER_TRAFFIC_LOG.html'>V_ENFORCER_TRAFFIC_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>32</td>
  <td class='comment detail'>Query the traffic activities for Enforcers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_GROUPS.html'>V_GROUPS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>14</td>
  <td class='comment detail'>Query the groups' information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_IPS.html'>V_IPS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Query the IPS content component.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_LAN_DEVICE_DETECTED.html'>V_LAN_DEVICE_DETECTED</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>21</td>
  <td class='comment detail'>Query the detected devices with human-readable IP address information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_LAN_DEVICE_EXCLUDED.html'>V_LAN_DEVICE_EXCLUDED</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>23</td>
  <td class='comment detail'>Query the known devices with human-readable IP address information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_MR_CLEAN.html'>V_MR_CLEAN</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>5</td>
  <td class='comment detail'>Query the the content component for the Mr Clean feature.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_NETWORK_SCAN_RESULT.html'>V_NETWORK_SCAN_RESULT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>0</td>
  <td class='comment detail'>Query the network scan results with human-readable IP address information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SECURITY_VIEW.html'>V_SECURITY_VIEW</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>10</td>
  <td class='comment detail'>Query the cross-technology security events.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SEM_COMPUTER.html'>V_SEM_COMPUTER</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>81</td>
  <td class='comment detail'>Query the computer information with human-readable IP address information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SEM_CONTENT.html'>V_SEM_CONTENT</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>7</td>
  <td class='comment detail'>Query the content revision information for clients.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SERVER_ADMIN_LOG.html'>V_SERVER_ADMIN_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>21</td>
  <td class='comment detail'>Query the administrator activities for servers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SERVER_CLIENT_LOG.html'>V_SERVER_CLIENT_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>21</td>
  <td class='comment detail'>Query the client activities for servers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SERVER_ENFORCER_LOG.html'>V_SERVER_ENFORCER_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>15</td>
  <td class='comment detail'>Query the Enforcer activities for servers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SERVER_POLICY_LOG.html'>V_SERVER_POLICY_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>18</td>
  <td class='comment detail'>Query the policy change activities for servers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SERVER_SYSTEM_LOG.html'>V_SERVER_SYSTEM_LOG</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>19</td>
  <td class='comment detail'>Query the system activities for servers.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SERVERS.html'>V_SERVERS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>14</td>
  <td class='comment detail'>Query the servers information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_SONAR.html'>V_SONAR</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>5</td>
  <td class='comment detail'>Query the the V_SONAR content component.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/V_VIRUS.html'>V_VIRUS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>22</td>
  <td class='comment detail'>Query the virus information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/VERSION.html'>VERSION</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>4</td>
  <td class='comment detail'>Keeps the schema version information.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/VIRUS.html'>VIRUS</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>23</td>
  <td class='comment detail'>Keeps the list of threats found in the network.</td>
  </tr>
 <tr class='tbl' valign='top'>  <td class='detail'><a href='tables/VIRUSCATEGORY.html'>VIRUSCATEGORY</a></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'></td>
  <td class='detail' align='right'>8</td>
  <td class='comment detail'>Lists and defines all possible kinds of threats.</td>
  </tr>
  <tr>
    <td class='detail'>&nbsp;</td>
    <td class='detail'>&nbsp;</td>
    <td class='detail'>&nbsp;</td>
    <td class='detail'>&nbsp;</td>
    <td class='comment detail'>&nbsp;</td>
  </tr>
  <tr class='tbl'>
    <td class='detail'><b>156 Tables</b></td>
    <td class='detail'>&nbsp;</td>
    <td class='detail'>&nbsp;</td>
    <td class='detail' align='right'><b>2,905</b></td>
    <td class='comment detail'>&nbsp;</td>
  </tr>
  <tr class='view'>
    <td class='detail'><b>0 Views</b></td>
    <td class='detail'>&nbsp;</td>
    <td class='detail'>&nbsp;</td>
    <td class='detail' align='right'><b>0</b></td>
    <td class='comment detail'>&nbsp;</td>
  </tr>
</table>
</div>
</body>
</html>
