<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - Table sem5.dbo.SYSTEM_REPORT</title>
  <link rel=stylesheet href='../schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    table='SYSTEM_REPORT';
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='../index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='../relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='../constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='../anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='../columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>Table <span title='Database'>sem5</span>.<span title='Schema'>dbo</span>.<span title='Table'>SYSTEM_REPORT</span></span><div style='padding: 0px 4px;'>Keeps the administrator-defined filters for the System logs.</div><p>
</td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%' border='0'>
<tr valign='top'><td class='container' align='left' valign='top'>
<form name='options' action=''>
 <label for='showRelatedCols'><input type=checkbox id='showRelatedCols'>Related columns</label>
 <label for='showConstNames'><input type=checkbox id='showConstNames'>Constraints</label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
 <label for='showLegend'><input type=checkbox checked id='showLegend'>Legend</label>
</form>
</td><td class='container' rowspan='2' align='right' valign='top'>
 <table class='legend' border='0'>
  <tr>
   <td class='dataTable' valign='bottom'>Legend:</td>
  </tr>
  <tr><td class='container' colspan='2'>
   <table class='dataTable' border='1'>
    <tbody>
    <tr><td class='primaryKey'>Primary key columns</td></tr>
    <tr><td class='indexedColumn'>Columns with indexes</td></tr>
    <tr class='impliedRelationship'><td class='detail'><span class='impliedRelationship'>Implied relationships</span></td></tr>
    <tr><td class='excludedColumn'>Excluded column relationships</td></tr>
    <tr><td class='legendDetail'>&lt; <em>n</em> &gt; number of related tables</td></tr>
   </table>
  </td></tr>
 </table>
&nbsp;
</td><tr valign='top'><td class='container' align='left' valign='top'>
<a name='columns'></a>
<table id='columns' class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th>Column</th>
  <th>Type</th>
  <th>Size</th>
  <th title='Are nulls allowed?'>Nulls</th>
  <th title='Is column automatically updated?'>Auto</th>
  <th title='Default value'>Default</th>
  <th title='Columns in tables that reference this column'><span class='notSortedByColumn'>Children</span></th>
  <th title='Columns in tables that are referenced by this column'><span class='notSortedByColumn'>Parents</span></th>
  <th title='Comments' class='comment'><span class='notSortedByColumn'>Comments</span></th>
</tr>
</thead>
<tbody valign='top'>
<tr class='odd'>
 <td class='detail'>SYSTEMFILTER_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='even'>
 <td class='primaryKey' title='Primary Key'>USER_ID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='primaryKey' title='Primary Key'>FILTERNAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='even'>
 <td class='detail'>STARTDATEFROM</td>
 <td class='detail'>datetime</td>
 <td class='detail' align='right'>16,3</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('19700101')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time filter start date.</td>
</tr>
<tr class='odd'>
 <td class='detail'>STARTDATETO</td>
 <td class='detail'>datetime</td>
 <td class='detail' align='right'>16,3</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('19700101')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Time filter end date</td>
</tr>
<tr class='even'>
 <td class='detail'>RELATIVEDATETYPE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>0 = The past week.<br />1 = The past month. <br />2 = The past three months. <br />3 = The past year. <br />4 = The past 24 hours. <br />5 = The current month.</td>
</tr>
<tr class='odd'>
 <td class='primaryKey' title='Primary Key'>SYSTEM_TYPE</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>1 = Administrative<br />2 = Client-Server Activity<br />3 = Server Activity<br />4 = Client Activity<br />5 = Enforcer Activity</td>
</tr>
<tr class='even'>
 <td class='detail'>SEVERITY</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>For Administrative, Client-Server, and Server Activity:<br />1000 = Error and above.<br />900 = Warning and above.<br />800 = Informational and above.<br />-1 = No filter (all).<br /><br />For Enforcer activity and client activity:<br />0 = Informational and above.<br />1 = Warning and above.<br />2 = Error and above.<br />3 = Fatal.<br />-1 = No filter (all).</td>
</tr>
<tr class='odd'>
 <td class='detail'>EVENT_ID</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>64</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Blank or a percent sign (%) in this field means no filtering.<br /> <br /> For the System > Administrative log:<br /> <br /> ADMIN_ADMIN_TYPES=Administrator events. Possible values:<br /> 4097 = The logon succeeded.<br /> 4098 = The logon failed.<br /> 4099 = The administrator logged out.<br /> 4050 = The account was locked.<br /> 4101 = The account was unlocked.<br /> 4102 = The account was disabled.<br /> 4103 = The account was enabled.<br /> 4104 = The administrator account was created.<br /> 4105 = The administrator account was deleted.<br /> 4106 = The administrator account was renamed.<br /> 4107 = The password was changed.<br /> 4108 = The administrator properties are changed.<br /> <br /> ADMIN_DOMAIN_TYPES = Domain events. Possible values are as follows:<br /> 4109 = The domain was created.<br /> 4110 = The domain was deleted.<br /> 4111 = The domain properties were changed.<br /> 4128 = The domain was disabled.<br /> 4129 = The domain was enabled.<br /> 4130 = The domain was renamed.<br /> <br /> ADMIN_GROUP_TYPES = Group events. Possible values are as follows:<br /> 8193 = The group was created.<br /> 8194 = The group was deleted.<br /> 8195 = The group was renamed.<br /> 8196 = The group was moved.<br /> 8197 = The group properties were changed.<br /> <br /> ADMIN_USER_TYPES = The user events. Possible values are as follows:<br /> 8198 = The user was created.<br /> 8199 = The user was deleted.<br /> 8200 = The user was moved.<br /> 8201 = The user was copied.<br /> 8202 = The user policy mode was switched.<br /> 8203 = The user properties were changed.<br /> <br /> ADMIN_COMPUTER_TYPES = Computer events. Possible values are as follows:<br /> 8204 = The computer was created.<br /> 8205 = The computer was deleted.<br /> 8206 = The computer was moved.<br /> 8207 = The computer was copied.<br /> 8208 = The computer policy mode was switched.<br /> 8209 = The computer properties were changed.<br /> <br /> ADMIN_IMPORT_TYPES = Import events. Possible values are as follows:<br /> 8210 = The Organizational Unit was imported.<br /> 8211 = The domain user was imported.<br /> 8212 = The LDAP user was imported.<br /> <br /> ADMIN_PACKAGE_TYPES = Package events. Possible values are as follows:<br /> 12289 = The package was created.<br /> 12290 = The package was deleted.<br /> 12291 = The package was exported.<br /> 12292 = The package was moved to the Recycle Bin.<br /> 12293 = The package is now current.<br /> 12294 = The package was added to another domain.<br /> 12295 = The package properties were changed.<br /> 12296 = The package deployment was created.<br /> 12297 = The package deployment was deleted.<br /> 12298 = The package deployment properties changed.<br /> 12299 = The package was updated.<br /> <br /> ADMIN_REPLICATION_TYPES = Replication events. Possible values are as follows:<br /> 16385 = The replication partner was registered.<br /> 16386 = The replication partner was deleted.<br /> 16400 = Replicate now.<br /> <br /> ADMIN_OTHER_TYPES = Other events. Possible values are as follows:<br /> 16387 = The remote site was deleted.<br /> 16388 = The site properties were changed.<br /> 16389 = The server properties were changed.<br /> 16390 = The database properties were changed.<br /> 16391 = The partner properties were changed.<br /> 16392 = The site license was changed.<br /> 16393 = The Enforcer license changed.<br /> 16394 = Replicate now.<br /> 16395 = Back up now.<br /> 16396 = The external logging properties were changed.<br /> 16397 = The site backup settings changed.<br /> 16398 = The server was deleted.<br /> 16399 = The server certificate changed.<br /> 16401 = Back up now.<br /> 16402 = The external logging properties were changed.<br /> 16403 = The site backup settings were changed.<br /> 16404 = The server was deleted.<br /> 16405 = Server certificate was changed.<br /> 16406 = The Enforcer group properties changed.<br /> <br /> <br /> For the System > Client-Server Activity log:<br /> <br /> 1 = The client registration succeeded.<br /> 2 = The client registration failed.<br /> 3 = The client reconnected.<br /> 4 = The client disconnected.<br /> 5 = The client downloaded the policy.<br /> 6 = The client downloaded the Intrusion Prevention policy.<br /> 7 = The client downloaded the sylink.xml.<br /> 8 = The client downloaded the Auto-Upgrade file.<br /> 9 = The server received the log.<br /> 10 = The log processing failed.<br /> 11 = The server received the learned application.<br /> 12 = The server received the client information.<br /> 13 = The client information processing failed.<br /> 14 = The hardware identity changed.<br /> 15 = The client downloaded the file fingerprint list.<br /> 20 = The client downloaded the content package.<br /> 22 = The client downloaded the command.<br /> <br /> <br /> For the System > Server Activity log:<br /> <br /> SERVER_EVENT_TYPES = Server events. Possible values are as follows:<br /> 257 = The server startup succeeded.<br /> 258 = The server startup failed.<br /> 259 = The server shut down gracefully.<br /> 260 = The server created.<br /> <br /> SERVER_AGENT_EVENT_TYPES = Database maintenance events. Possible values are as follows:<br /> 267 = The client sweep task started.<br /> 268 = The client sweep task summary.<br /> 269 = The client sweep task succeeded.<br /> 270 = The client sweep task failed.<br /> 271 = The database logs have been swept.<br /> <br /> SERVER_BACKUP_EVENT_TYPES = Database backup events. Possible values are as follows:<br /> 1025 = The backup connection failed.<br /> 1026 = The backup data fetch failed.<br /> 1027 = The backup file write failed.<br /> 1028 = The backup unknown failed.<br /> 1029 = The backup succeeded.<br /> 1030 = The backup started.<br /> <br /> SERVER_RADIUS_EVENT_TYPES = RADIUS server events. Possible values are as follows:<br /> 1283 = Failed to start RADIUS server. The RADIUS port may be in use by another process.<br /> 1284 = Failed to start RADIUS server. Set Non-Block I/O socket failed.<br /> 1285 = Failed to start RADIUS Server. Create Socket error.<br /> <br /> SERVER_REPLICATION_EVENT_TYPES = Replication events. Possible values are as follows:<br /> 769 = The replication from the remote site started.<br /> 770 = The replication failed to log on to the remote site.<br /> 771 = Unable to fetch the changed data from the remote site.<br /> 772 = The replication finished successfully.<br /> 773 = The replication failed.<br /> 774 = The replication merge failed.<br /> 775 = Unable to connect to the remote site.<br /> 776 = The name was changed to resolve a merge conflict.<br /> 777 = The group full path name was too long for replication.<br /> 778 = The retrieval of the local changed data for the remote site started.<br /> 779 = The retrieval of the local changed data for the remote site finished successfully.<br /> 780 = The retrieval of the local changed data for the remote site failed.<br /> 781 = Replication has been chosen as the deadlock victim and was killed by the database.<br /> 782 = The replication data was received.<br /> <br /> SERVER_IMPORT_EVENT_TYPES = Import events. Possible values are as follows:<br /> 264 = The Organizational Unit import started.<br /> 265 = The Organization Unit import succeeded.<br /> 266 = The Organization Unit import failed.<br /> <br /> SERVER_INTRUSION_PREVENTION_EVEN = Intrusion Prevention policy content updates. Possible values are as follows:<br /> 1537 = Added the intrusion prevention library.<br /> 1538 = Deleted the intrusion prevention library.<br /> 1539 = Updated the intrusion prevention library.<br /> 1540 = The intrusion prevention library was up to date.<br /> <br /> SERVER_LU_EVENT_TYPES = LiveUpdate events. Possible values are as follows:<br /> 1793 = LiveUpdate started.<br /> 1794 = LiveUpdate succeeded.<br /> 1795 = LiveUpdate failed.<br /> 1796 = The LiveUpdate manual task succeeded.<br /> 1797 = The LiveUpdate manual task failed.<br /> 1798 = The LiveUpdate retry started.<br /> 1799 = The LiveUpdate retry succeeded.<br /> 1800 = The LiveUpdate retry failed, and will try again.<br /> 1801 = The LiveUpdate manual task started.<br /> 1802 = The LiveUpdate retry exceeded the maximum retry window.<br /> 1803 = The LiveUpdate retry failed, and will try again.<br /> 1804 = The LiveUpdate retry passed the scheduled time.<br /> 1805 = The process LiveUpdate All launched.<br /> 1806 = The process LiveUpdate All exited abnormally.<br /> 1807 = LiveUpdate tried the next possible server.<br /> 1808 = The process LiveUpdate All finished.<br /> 1809 = The process LiveUpdate All failed to launch.<br /> 1810 = LiveUpdate is uploading content.<br /> 1811 = The LiveUpdate file path does not exist.<br /> 1812 = The LiveUpdate Content Catalog file has been inserted.<br /> 1813 = The LiveUpdate Content Catalog file has been updated.<br /> 1814 = The client package has been downloaded.<br /> 1815 = The client package patching failed.<br /> 1816 = New LiveUpdate content has been downloaded.<br /> 1817 = LiveUpdate has the wrong URL parameter.<br /> 1824 = Antivirus and antispyware definitions failed to update.<br /> 1825 = The download was current.<br /> 1826 = The LiveUpdate re-run was triggered by a content catalog update.<br /> 1818 = LiveUpdate failed to download content.<br /> 1819 = LiveUpdate content was cleaned up.<br /> 1820 = The Host Integrity template has been updated.<br /> 1821 = LiveUpdate timed out.<br /> 1822 = The LiveUpdate schedule was updated.<br /> <br /> SERVER_NET_AUDIT_EVENT_TYPES = Find unmanaged computers events. Possible values are as follows:<br /> 2049 = A search for uncliented hosts started.<br /> 2050 = A search for uncliented hosts finished normally.<br /> 2051 = A search for uncliented hosts finished abnormally<br /> 2052 = A client remote started.<br /> 2053 = The client remote finished normally.<br /> 2054 = The client remote finished abnormally.<br /> <br /> SERVER_OTHER_EVENT_TYPES = Other events. Possible values are as follows:<br /> 261 = The site was created.<br /> 262 = The package was published.<br /> 263 = The site license has been exceeded.<br /> 272 = The server upgrade succeeeded.<br /> 273 = Scheduled reporting failed.<br /> 274 = Security risk rating summary.<br /> 1281 = An unexpected exception has occurred.<br /> 1282 = A connect to the mail server failed.<br /> 1286 = Server error.<br /> <br /> <br /> For the System > Client Activity log. Event IDs are listed by hexadecimal value.<br /> <br /> AGENT_SYSTEM_INSTALL_EVENT_TYPES = Installation events. Possible values are as follows:<br /> 0x12070001 = Internal error.<br /> 0x12070101 = Installation complete.<br /> 0x12070102 = Restart recommended.<br /> 0x12070103 = Restart required.<br /> 0x12070104 = Installation failed.<br /> 0x12070105 = Uninstallation complete.<br /> 0x12070106 = Uninstallation failed.<br /> 0x12071037 = Symantec Endpoint Protection installed.<br /> 0x12071038 = Symantec Firewall installed.<br /> 0x12071039 = Uninstallation.<br /> 0x1207103A = The uninstallation rolled back.<br /> <br /> AGENT_SYSTEM_SERVICE_EVENT_TYPES = Service events. Possible values are as follows:<br /> 0x12070201 = The service is starting.<br /> 0x12070202 = The service started.<br /> 0x12070203 = The service failed to start.<br /> 0x12070204 = The service stopped.<br /> 0x12070205 = The service failed to stop.<br /> 0x1207021A = Attempted to stop the service.<br /> <br /> AGENT_SYSTEM_CONFIG_EVENT_TYPES = Configuration events. Possible values are as follows:<br /> 0x12070206 = The configuration import completed.<br /> 0x12070207 = The configuration import failed with an error.<br /> 0x12070208 = The configuration export completed.<br /> 0x12070209 = The configuration export failed with an error.<br /> <br /> AGENT_SYSTEM_HI_EVENT_TYPES = Host Integrity events. Possible values are as follows:<br /> 0x12070210 = Host Integrity was disabled.<br /> 0x12070211 = Host Integrity was enabled.<br /> <br /> AGENT_SYSTEM_IMPORT_EVENT_TYPES = Import events. Possible values are as follows:<br /> 0x12070214 = Successfully imported an advanced rule.<br /> 0x12070215 = Failed to import an advanced rule.<br /> 0x12070216 = Successfully exported an advanced rule.<br /> 0x12070217 = Failed to export an advanced rule.<br /> <br /> AGENT_SYSTEM_CLIENT_EVENT_TYPES = Client events. Possible values are as follows:<br /> 0x12070218 = The client engine was enabled.<br /> 0x12070219 = The client engine was disabled.<br /> 0x12071046 = Proactive Threat Scanning is not supported on this platform.<br /> 0x12071047 = Proactive Threat Scanning failed to load with an error.<br /> <br /> AGENT_SYSTEM_SERVER_EVENT_TYPES = Server events. Possible values are as follows:<br /> 0x12070301 = The server connected.<br /> 0x12070302 = The server did not respond.<br /> 0x12070303 = The server connection failed.<br /> 0x12070304 = The server disconnected.<br /> 0x120B0001 = Cannot reach the server.<br /> 0x120B0002 = Reconnected to the server.<br /> <br /> AGENT_SYSTEM_PROFILE_EVENT_TYPES = Policy events. Possible values are as follows:<br /> 0x12070306 = A new policy was received.<br /> 0x12070307 = A new policy was applied.<br /> 0x12070308 = A new policy failed to apply.<br /> 0x12070309 = Cannot download the policy.<br /> 0x120B0005 = Cannot download the policy<br /> 0x1207030A = Have latest policy<br /> 0x120B0004 = Have latest policy<br /> <br /> AGENT_SYSTEM_AV_EVENT_TYPES = Antivirus engine events. Possible values are as follows:<br /> 0x12071006 = A scan omission occurred.<br /> 0x1207100B = Virus-like behavior was detected.<br /> 0x1207100C = The configuration changed.<br /> 0x12071010 = The definition file downloaded.<br /> 0x12071012 = Item sent to the Quarantine Server.<br /> 0x12071013 = Item delivered To Symantec<br /> 0x12071014 = Security Response Backup<br /> 0x12071015 = The scan was aborted.<br /> 0x12071016 = Symantec Endpoint Protection Auto-Protect failed to load due to an error.<br /> 0x12071017 = Symantec Endpoint Protection Auto-Protect enabled.<br /> 0x12071018 = Symantec Endpoint Protection Auto-Protect disabled.<br /> 0x1207101A = The scan was delayed.<br /> 0x1207101B = The scan was restarted.<br /> 0x12071027 = Symantec Endpoint Protection has old virus definitions.<br /> 0x12071041 = The scan was suspended.<br /> 0x12071042 = The scan resumed.<br /> 0x12071043 = The scan duration was too short.<br /> 0x12071045 = Scan enhancements failed.<br /> <br /> AGENT_SYSTEM_LICENSE_EVENT_TYPES = License events. Possible values are as follows:<br /> 0x1207101E = The license status generated a warning.<br /> 0x1207101F = The license status generated an error.<br /> 0x12071020 = The license is in its grace period.<br /> 0x12071023 = The license is installed.<br /> 0x12071025 = The license is up to date.<br /> <br /> AGENT_SYSTEM_SECURITY_EVENT_TYPES = Security events. Possible values are as follows:<br /> 0x1207102B = The computer is not compliant with security policy.<br /> 0x1207102C = The computer is compliant with security policy.<br /> 0x1207102D = The computer is reporting a Tamper Protection alert.<br /> <br /> AGENT_SYSTEM_OTHER_EVENT_TYPES = Other events. Possible values are as follows: <br /> 0x1207020A = The email sent successfully.<br /> 0x1207020B = The email failed to send.<br /> 0x1207020C = The update completed.<br /> 0x1207020D = The update failed.<br /> 0x1207020E = The location changed manually.<br /> 0x1207020F = The location changed.<br /> 0x12070212 = An old version of ras.dll was detected.<br /> 0x12070213 = AutoUpgrade postponed.<br /> 0x12070305 = Mode changed.<br /> 0x1207030B = Cannot apply the Host Integrity script.<br /> 0x12070500 = A system message was received from device control.<br /> 0x12070600 = A system message was received from the anti-buffer overflow driver.<br /> 0x12071021 = A warning message was received indicating "Access Denied".<br /> 0x12071022 = A log forwarding error occurred.<br /> 0x12071044 = The client moved.<br /> <br /> <br /> For the System > Enforcer Activity log. Event IDs are listed by hexadecimal value.<br /> <br /> ENFORCER_POLICY_MANAGER_EVENT_TY = Management events. Possible values are as follows:<br /> 0x101 = Connected to Policy Manager.<br /> 0x102 = Lost connection to Policy Manager.<br /> 0x103 = Applied the policy downloaded from Policy Manager.<br /> 0x104 = Failed to apply the policy downloaded from Policy Manager.<br /> 0x105 = Applied the Policy Manager configuration.<br /> 0x106 = Failed to apply the Policy Manager configuration.<br /> 0x107 = Applied the Policy Manager configuration.<br /> 0x108 = Failed to apply the Policy Manager configuration.<br /> <br /> ENFORCER_ENFORCER_EVENT_TYPES = Enforcer events. Possible values are as follows:<br /> 0x201 = The Enforcer started.<br /> 0x202 = The Enforcer stopped.<br /> 0x203 = The Enforcer paused.<br /> 0x204 = The Enforcer resumed.<br /> 0x205 = The Enforcer disconnected from the server.<br /> 0x301 = The Enforcer failover enabled.<br /> 0x302 = The Enforcer failover disabled.<br /> 0x303 = The Enforcer is in standby mode.<br /> 0x304 = The Enforcer is in primary mode.<br /> 0x305 = Enforcer short.<br /> 0x306 = Enforcer loop.<br /> <br /> ENFORCER_ENABLE_EVENT_TYPES = Enable events. Possible values are as follows:<br /> 0x401 = The forward engine is paused.<br /> 0x402 = The forward engine started.<br /> 0x403 = The DNS enforcer enabled.<br /> 0x404 = The DNS enforcer disabled.<br /> 0x405 = The DHCP enforcer enabled.<br /> 0x406 = The DHCP enforcer disabled.<br /> 0x407 = "Allow all" is enabled.<br /> 0x408 = "Allow all" is disabled.<br /> <br /> ENFORCER_PROFILE_EVENT_TYPES = Policy events. Possible values are as follows:<br /> 0x501 = The seat number changed.<br /> 0x601 = Failed to create the policy parser.<br /> 0x602 = Failed to import the policy that was downloaded from Policy Manager.<br /> 0x603 = Failed to export the policy that was downloaded from Policy Manager.<br /> 0x701 = The customized attribute was incorrect.</td>
</tr>
<tr class='even'>
 <td class='detail'>EVENT_DESC</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Description of the event. Usually, the first line of the description is treated as the summary.</td>
</tr>
<tr class='odd'>
 <td class='detail'>MSG_ID</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>255</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>This field stores the hard-coded English string key found to the left of the equal sign (=).  To the right is a description of the kinds of error messages that will be queried. % or blank in this field means no filtering (all records).  See the following for the list of corresponding MSG IDs that fall into each bucket.<br /><br />MSG IDs:<br /><br />ERROR_MSG_x1 = Unexpected server error.<br />ERROR_MSG_x2 = Unexpected console error.<br />ERROR_MSG_x3 = Failed to connect to the server. Make sure that the server is running and your session has not timed out. If you can reach the server but cannot log on, make sure that you provided the correct parameters. If you are experiencing network issues, contact your system administrator.<br />ERROR_MSG_x4 = Unknown response.<br />ERROR_MSG_x5 = No response code.<br />ERROR_MSG_x6 = Invalid response code.<br />ERROR_MSG_x7 = You are no longer connected to the Symantec Endpoint Protection Manager. You must log on again to continue.<br />ERROR_MSG_x8 = Logon failed.<br />ERROR_MSG_x9 = Invalid action.<br />ERROR_MSG_xA = Unable to connect to the database.<br />ERROR_MSG_xB = Invalid parameter.<br />ERROR_MSG_xC = Administrator name is already in use.<br />ERROR_MSG_xD = Administrator not found.<br />ERROR_MSG_xE = Group not found.<br />ERROR_MSG_xF = Invalid response data.<br />ERROR_MSG_x10 = Site not found.<br />ERROR_MSG_x11 = Query not found.<br />ERROR_MSG_x12 = The results returned are more than 100 records.<br />ERROR_MSG_x13 = Only select query is allowed.<br />ERROR_MSG_x14 = Invalid query statement.<br />ERROR_MSG_x15 = The data type you selected is not supported.<br />ERROR_MSG_x16 = You cannot delete all the administrators.<br />ERROR_MSG_x17 = The action type is null.<br />ERROR_MSG_x18 = The action type is invalid.<br />ERROR_MSG_x19 = The object GUID is null.<br />ERROR_MSG_x1A = The object GUID is invalid.<br />ERROR_MSG_x1B = The transaction GUID is null.<br />ERROR_MSG_x1C = The transaction GUID is invalid.<br />ERROR_MSG_x1D = The domain GUID is null.<br />ERROR_MSG_x1E = The domain GUID is invalid.<br />ERROR_MSG_x1F = The object type is null.<br />ERROR_MSG_x20 = The object type is invalid.<br />ERROR_MSG_x21 = There is no connection.<br />ERROR_MSG_x22 = The connection is invalid.<br />ERROR_MSG_x23 = The file fingerprint is null.<br />ERROR_MSG_x24 = The policy update is invalid.<br />ERROR_MSG_x25 = Request is invalid.<br />ERROR_MSG_x26 = The SQL query is null.<br />ERROR_MSG_x27 = The USN is null.<br />ERROR_MSG_x28 = The USN is invalid.<br />ERROR_MSG_x29 = This method with a domain parameter can only called by System Administrators.<br />ERROR_MSG_x2A = Invalid SQL query type.<br />ERROR_MSG_x2B = Invalid SQL query parameter.<br />ERROR_MSG_x2C = The administrator's user name or password is incorrect. Enter a valid user name and password.<br />ERROR_MSG_x2D = Domain is disabled.<br />ERROR_MSG_x2E = The administrator account has no access.<br />ERROR_MSG_x2F = The administrator account is locked.<br />ERROR_MSG_x30 = Domain not found.<br />ERROR_MSG_x31 = The management server does not support RSA SecurID logon.<br />ERROR_MSG_x32 = The transaction does not exist.<br />ERROR_MSG_x33 = The transaction rollback failed.<br />ERROR_MSG_x34 = The transaction commit failed.<br />ERROR_MSG_x35 = The transaction start failed.<br />ERROR_MSG_x36 = The object cannot be found.<br />ERROR_MSG_x37 = The object's content is corrupt.<br />ERROR_MSG_x38 = The object is concurrently updating.<br />ERROR_MSG_x39 = The datastore is not connected.<br />ERROR_MSG_x3A = Datastore error.<br />ERROR_MSG_x3B = The target site belongs to a different group of sites.<br />ERROR_MSG_x3C = The top level group cannot be deleted.<br />ERROR_MSG_x3D = Unable to delete this group because there are still clients or subgroups in the group.<br />ERROR_MSG_x3E = Unable to delete this group because there are still clients in the group.<br />ERROR_MSG_x40 = The license has expired.<br />ERROR_MSG_x41 = You have reached the limit of your license.<br />ERROR_MSG_x42 = Your license doesn't support this feature.<br />ERROR_MSG_x43 = Invalid Site License.<br />ERROR_MSG_x44 = You cannot access this server from this IP address.<br />ERROR_MSG_x45 = Invalid certificate file.<br />ERROR_MSG_x46 = Invalid private key file.<br />ERROR_MSG_x47 = Invalid keystore file.<br />ERROR_MSG_x48 = Invalid keystore password.<br />ERROR_MSG_x49 = Failed to write certificate on server.<br />ERROR_MSG_x4A = The length of an administrator name must be between {0} and {1} characters.<br />ERROR_MSG_x4B = The administrator name cannot contain any one of {0} characters.<br />ERROR_MSG_x4C = The administrator name should not be all dots or spaces.<br />ERROR_MSG_x4D = An Active Directory node cannot be moved.<br />ERROR_MSG_x4E = The global or temporary groups cannot be moved.<br />ERROR_MSG_x4F = The group cannot be moved to any Active Directory node.<br />ERROR_MSG_x50 = The group cannot be moved to the temporary group.<br />ERROR_MSG_x51 = The Organizational Unit is already in use.<br />ERROR_MSG_x52 = You must enter a hostname.<br />ERROR_MSG_x53 = Failed to connect to the directory server.<br />ERROR_MSG_x54 = Failed to read {0}.<br />ERROR_MSG_x55 = The action is null.<br />ERROR_MSG_x56 = The restore file is invalid.<br />ERROR_MSG_x57 = Failed to create a folder to which to publish the package.<br />ERROR_MSG_x58 = You cannot use the same site name as a remote replication site.<br />ERROR_MSG_x59 = The {0} group was not found.<br />ERROR_MSG_x5A = The group path is not valid.<br />ERROR_MSG_x5B = The partner is not found.<br />ERROR_MSG_x5C = The name is a duplicate.<br />ERROR_MSG_x5D = A site referenced by the installation instance was not found.<br />ERROR_MSG_x5E = The local site seems to have been deleted from the installation instance.<br />ERROR_MSG_x5F = The Organizational Unit group ID is invalid.<br />ERROR_MSG_x60 = The domain ID is invalid in the session when trying to import the Organizational Unit.<br />ERROR_MSG_x61 = The destination group is same as the source group.<br />ERROR_MSG_x62 = The URL you specified is not accessible. This may be caused by network connection problems, or the web site is down.<br />ERROR_MSG_x63 = The management server is running another process. Check the server system log for details.<br />ERROR_MSG_x64 = Invalid key password.<br />ERROR_MSG_x65 = Browse Network Error. Make sure that the Computer Browser service in Windows is started and running.<br />ERROR_MSG_x70 = The domain name is already in use.<br />ERROR_MSG_x71 = The management server can only query users from the domains it belongs to.<br />ERROR_MSG_x72 = The management server can only filter users from the domains it belongs to.<br />ERROR_MSG_x73 = The administrator account does not have permission to perform the requested task.<br />ERROR_MSG_x74 = Your hard disk {0} space is less than {1}MB and impacts the performance of Symantec Endpoint Protection Manager. You should delete some files to free up space. Symantec recommends that you have a minimum of {2}GB of free disk space.<br />ERROR_MSG_x75 = Your hard disk {0} space is less than {1}MB. Symantec Endpoint Protection Manager requires more disk space to complete certain tasks. Please delete some files to free up some space. Symantec recommends that you have a minimum of {2}GB of free disk space.<br />ERROR_MSG_x80 = The group full name is too long.<br />ERROR_MSG_x81 = Failed to resolve naming conflict.<br />ERROR_MSG_x82 = No response from the remote server.<br />ERROR_MSG_x83 = Email sending failed.<br />ERROR_MSG_x84 = Failed to check duplicate names.<br />ERROR_MSG_x85 = The legacy client is not found.<br />ERROR_MSG_x86 = The file is not found.<br />ERROR_MSG_x87 = An IO exception occurred.<br />ERROR_MSG_x88 = There were one or more errors when parsing the file from the client.<br />ERROR_MSG_x89 = A validation exception occurred.<br />ERROR_MSG_x90 = Unexpected parameter value.<br />ERROR_MSG_x91 = Missing named version.<br />ERROR_MSG_x92 = Missing PackageLuInfo.<br />ERROR_MSG_x93 = Missing LuCatalog File.<br />ERROR_MSG_x94 = Missing LuContentPolicy.<br />ERROR_MSG_x95 = Symantec Endpoint Protection Manager could not connect to the target directory server. Check the directory server configuration, and try again.<br />ERROR_MSG_x96 = Failed to connect to the specified replication partner server. Verify that the server name and port are correct.<br />ERROR_MSG_x97 = Invalid Syslog server name.<br />ERROR_MSG_x98 = The management server has detected and ignored one or more invalid or duplicate entries. Check the following entries in your directory server:<br />ERROR_MSG_x99 = Domain has been disabled.<br />ERROR_MSG_x9A = The replication partner does not run the same version as the local site.<br />ERROR_MSG_x9B = You cannot log on to the console because the server is not synchronized with the database. Upgrade the server, and then log on to the console.<br />ERROR_MSG_x9C = The replicated software package cannot be found in the cache.<br />ERROR_MSG_x9D = Remote site [{0}] is downloading LiveUpdate contents and cannot prepare the data until the next round of replication.<br />ERROR_MSG_x9E = Remote site [{0}] failed to prepare the data for replication.<br />ERROR_MSG_x9F = Remote site {0} blocks new clients. The client cannot register with remote site {0}.<br />ERROR_MSG_xA0 = Failed to connect to {0}. Make sure the server can ping or resolve this domain.<br />ERROR_MSG_xA1 = Unable to load binary file.<br />ERROR_MSG_xA2 = Error occurred during unzip operation.<br />ERROR_MSG_xA3 = Unable to load group profile.<br />ERROR_MSG_xA4 = Unable to generate packlist file.<br />ERROR_MSG_xA5 = Unable to modify config.xml.<br />ERROR_MSG_xA6 = Unable to modify setAid.ini file.<br />ERROR_MSG_xA7 = Unable to generate single .exe.<br />ERROR_MSG_xA8 = Unable to query database.<br />ERROR_MSG_xA9 = Unable to load server list.<br />ERROR_MSG_xAA = Unable to load software package data.<br />ERROR_MSG_xAF = Not enough disk space on the server. Cannot continue.<br />ERROR_MSG_xB0 = Your temporary password could not be activated. Make sure that the account for which you requested a password is valid and try again.<br />ERROR_MSG_xB1 = You must use the most recent link that you were sent to reset your password. If the link does not work, copy the link from the email and paste it into your browser address bar.<br />ERROR_MSG_xB2 = Domain not found.<br />ERROR_MSG_xB3 = No email account associated with that logon.<br />ERROR_MSG_xB4 = The server cannot send the email message to the administrator. Check that the email server is connected, or that the email address (and email credentials) for this administrator are correct.<br />ERROR_MSG_xB5 = Invalid administrator name.<br />ERROR_MSG_xB6 = Reset password failed.<br />ERROR_MSG_xB7 = Email server has not been configured yet.<br />ERROR_MSG_xB8 = You do not have permission to reset the administrator password. Contact the system administrator at this site to enable the reset password option.<br />ERROR_MSG_xB9 = Server failed to generate a random password.<br />ERROR_MSG_xBA = You must wait five minutes before you can request another temporary password.<br />ERROR_MSG_xBB = The URL to activate this password is incorrect. Copy and paste the URL from the email message again.<br />ERROR_MSG_xBC = You have successfully activated your password reset request. You can now use the new password to log on to Symantec Endpoint Protection Manager.<br />ERROR_MSG_xBD = Your password reset link has expired. You must use the link within eight hours of receiving it. To reset your password, click "Forgot your password?" in the Symantec Endpoint Protection Manager console logon window.<br />ERROR_MSG_xBE = Unable to process password reset request. A valid IP address for the Symantec Endpoint Protection Manager was not found. Please select or enter a valid IP address and try again.<br />ERROR_MSG_xBF = The password cannot be reset because your authentication mode is not set to Symantec Endpoint Protection Manager authentication. Any Symantec Endpoint Protection administrator can change your password.<br />ERROR_MSG_xC0 = The parameters that were passed for the network scan are invalid.<br />ERROR_MSG_xC1 = The user cancelled the network scan.<br />ERROR_MSG_xC2 = The network scan timed out. Try to run the scan again.<br />ERROR_MSG_xC3 = The network scan could not be completed because the .dlls+A192 for Windows ICMP ping could not be found.<br />ERROR_MSG_xC4 = The network scan could not be completed because the auditparams.txt file is invalid or missing.<br />ERROR_MSG_xC5 = The network scan could not be completed because of an unknown error. Try to run the scan again later.<br />ERROR_MSG_xC6 = The network scan timed out for some of the target IP addresses.<br />ERROR_MSG_xC7 = Unable to load package data. Cannot continue.<br />ERROR_MSG_xC8 = Not enough disk space on the server. Cannot continue.<br />ERROR_MSG_xC9 = Failed to copy Host Integrity (HI) Content Library to install packages.<br />ERROR_MSG_xCA = The logon response from the remote partner is null.<br />ERROR_MSG_xCB = License information from the remote server is not available.<br />ERROR_MSG_xCC = The server schema version on the local server is newer than the server schema version of the replication partner on the remote site.  Please upgrade the remote server to ensure that the versions match.<br />ERROR_MSG_xCD = License information from the remote server is not available.<br />ERROR_MSG_xCE = The server schema version on the local server is older than the server schema version of the replication partner on the remote site.  Please upgrade the local server to ensure that the versions match.<br />ERROR_MSG_xCF = Remote server is not an Enterprise Server.<br />ERROR_MSG_xD0 = Replication partnership has been deleted from remote site.<br />ERROR_MSG_xD1 = Replication partnership has been setup between this site and remote site.<br />ERROR_MSG_xD2 = Invalid password for replication partnership logon.<br />ERROR_MSG_xD3 = Copy license file to install packages failed.<br />ERROR_MSG_xD4 = The time difference between the local site and the remote site is more than 10 minutes. Please synchronize server times to ensure correct replication of data.<br />ERROR_MSG_xD5 = The export folder path is too long. This is probably because the installation path for Symantec Endpoint Protection Manager is too long.<br />ERROR_MSG_xD6 = Unable to generate a package in .zip format.<br />ERROR_MSG_xE1 = Invalid administrator name.<br />ERROR_MSG_xE2 = An error occurred while verifying the signature of your ticket. Contact the administrator to resolve this issue.<br />ERROR_MSG_xE3 = The ticket signature from a certificate keystore is invalid. Contact the administrator to rectify this issue.<br />ERROR_MSG_xE4 = The signed data length received on the ticket is invalid. Contact the administrator to rectify this issue.<br />ERROR_MSG_xE5 = Ticket version not supported by current Symantec Endpoint Protection installation. Contact the administrator to rectify this issue.<br />ERROR_MSG_xE6 = The issue date for the ticket is invalid. Check that system times for the two servers are synchronized.<br />ERROR_MSG_xE7 = The logon ticket is expired. This can be due to timing differences in servers or an expired ticket being used for logon. Contact the administrator.<br />ERROR_MSG_xE8 = The Symantec Endpoint Protection domain you are trying to access is currently disabled.<br />ERROR_MSG_xE9 = The username used for logon is invalid. Contact the administrator to verify that the Symantec Endpoint Protection account associated with your account is valid.<br />ERROR_MSG_xEA = Cannot add root.<br />ERROR_MSG_xEB = Cannot delete root.<br />ERROR_MSG_xEC = The Symantec Endpoint Protection domain used for logon is invalid. Contact the administrator to verify that the Symantec Endpoint Protection domain associated with your account is valid.<br />ERROR_MSG_xED = The product you are trying to access is not registered. Contact the administrator to verify the registration with the required Symantec Endpoint Protection server.<br />ERROR_MSG_xEE = An error occurred while validating the ticket for your logon request. Try logging on again and if the error persists, contact the administrator.<br />ERROR_MSG_xEF = The specified user credentials cannot be used to logon for the current registration. Contact the administrator to update your Symantec Endpoint Protection account mapping.<br />ERROR_MSG_xF1 = LiveUpdate failed.<br />ERROR_MSG_xF2 = The new password must be different from the old password. Try again.<br />ERROR_MSG_xF3 = The version of Symantec Endpoint Protection Manager that you are trying to run is not the same as the version you are trying to connect to. This situation can occur between replication partners, or between the remote console and the management server. Upgrade any replication partners, or download the correct version of the remote console from the management server.<br />ERROR_MSG_xF4 = Email sending directly to the mail server failed.<br />ERROR_MSG_xF5 = The latest contents are missing.<br />ERROR_MSG_xF6 = The latest contents are missing.<br />ERROR_MSG_xF7 = An error occurred while validating the certificate for your logon request. Please try logging on again and if the error persists, contact the administrator.<br />ERROR_MSG_xF8 = Create domain failed. The specified domain ID is already in use. Choose another domain ID.<br />ERROR_MSG_xF9 = LDAP Authentication Failed [path={0}, user={1}]. It may fail due to an invalid account name or password, or the account is currently locked out by domain security policy.<br />ERROR_MSG_xFA = Your server certificate is not validated. If you trust the server, you must accept the certificate. Log in again and if the error persists, contact your administrator.<br />ERROR_MSG_xFB = Your command is already entered to be sent to your some of the clients. See the log file for details. Your command will be sent to the client shortly. Check the Command Status on the Monitors page to see the progress of your command.<br />ERROR_MSG_xFC = Your command is already entered to be sent to your clients. No new entries added. See log file for details. Your command will be sent to the client shortly. Check the Command Status on the Monitors page to see the progress of your command.<br />ERROR_MSG_xFD = You must enable at least one domain before you can log on to the Symantec Endpoint Protection Manager console.<br />ERROR_MSG_xFE = You must create a domain before you can log on to the Symantec Endpoint Protection Manager console.<br />ERROR_MSG_xFF = You are not authorized to execute this request.<br />ERROR_MSG_x100 = Request could not be authorized.<br />ERROR_MSG_x101 = Only system administrator account is allowed.<br />ERROR_MSG_x102 = Could not log on to the server because of a hostname mismatch. Learn more at http://www.symantec.com/docs/TECH205165<br />ERROR_MSG_x103 = Could not browse the network. The Bonjour service is missing. For more information, see the Technical Support article for installing the Bonjour service (http://www.symantec.com/docs/TECH213283).<br />ERROR_MSG_x104 = Could not browse the network. The Bonjour service is stopped. For more information, see the Technical Support article for installing the Bonjour service (http://www.symantec.com/docs/TECH213283).<br />ERROR_MSG_x105 = Failed to confirm the server certificate before the request timed out.<br />ERROR_MSG_x106 = The specified file is not a valid known_hosts file. Choose a valid file and try again.<br />ERROR_MSG_x107 = The host key for host {0} does not match. Verify the identity of the host or provide an updated known_hosts file and try again.<br />ERROR_MSG_x108 = The host {0} could not be found in the specified file. Remove the host from the list or provide an updated file that contains the correct host information and try again.<br />ERROR_MSG_x109 = An unknown error occurred while validating the host {0} against the specified file.<br />ERROR_MSG_x10A = The setting cannot be updated. This error might occur because the setting was already modified by another administrator. Refresh the management console and try to modify the setting again. If the error persists, a system administrator should run the Database Validation tool to confirm that the database passes a validation check.<br />ERROR_MSG_x10B = Password verification threshold exceeded.<br />ERROR_MSG_x200 = Failed to synchronize with the directory server {0}. Check the directory server settings in the management console and try again.<br /><br />Error message buckets as used in the SYSTEM_REPORT table, field MSG_ID:<br />ERR_SERVER' = array('9', 'A', 'B', 'C', 'D', 'E', 'F', '10', '11', '12', '13', '14', '15', '16');<br />ERR_INVALID_PARAMETER' = array('17', '18', '19', '1A', '1B', '1C', '1D', '1E', '1F', '20', '21', '22', '23', '24');<br />ERR_GENERAL' = array('1','2','3','4','5','6','7','8');<br />ERR_ROOT' = array('2A', '2B');<br />ERR_AUTHENTICATION' = array('2C', '2D', '2E', '2F', '30', '31', '4A', '4B', '4C');<br />ERR_METADATA' = array('36', '37', '38');<br />ERR_TRANSACTION' = array('32', '33', '34', '35');<br />ERR_DATASTORE' = array('39', '3A', '3B');<br />ERR_LICENSE' = array('40', '41', '42', '43');<br />ERR_CERTIFICATE' = array('45', '46', '47', '48', '49');<br />ERR_GROUP' = array('4D', '4E', '4F', '50');<br />ERR_FILE' = array('86','87', '88', '89', '90');<br />ERR_LIVEUPDATE' = array('92','93','94','97');<br />ERR_OTHER' = array('29', '3C', '3D', '44', '54', '57', '58', '59', '5A', '5D', '5E', '5F', '60', '62', '70', '71', '80', '81', '82', '83', '84', '85','91','95','96');<br />ERR_NONE' = array(-1);<br /> <br /><br />For System > Administrative:<br />ERR_SERVER=Server error messages<br />ERR_INVALID_PARAMETER=Invalid parameter error messages<br />ERR_GENERAL=General error messages<br />ERR_ROOT=Root error messages<br />ERR_AUTHENTICATION=Logon-related error messages<br />ERR_METADATA=Metadata error messages<br />ERR_TRANSACTION=Transaction error messages<br />ERR_DATASTORE=Datastore error messages<br />ERR_LICENSE=License error messages<br />ERR_CERTIFICATE=Certificate error messages<br />ERR_GROUP=Group error messages<br />ERR_FILE=File-related error messages<br />ERR_LIVEUPDATE=LiveUpdate error messages<br />ERR_OTHER=Other error messages<br />ERR_NONE=None<br /><br />For System > Server Activity:<br />ERR_SERVER=Server error messages<br />ERR_INVALID_PARAMETER=Invalid parameter error messages<br />ERR_GENERAL=General error messages<br />ERR_ROOT=Root error messages<br />ERR_AUTHENTICATION=Logon-related error messages<br />ERR_METADATA=Metadata error messages<br />ERR_TRANSACTION=Transaction error messages<br />ERR_DATASTORE=Datastore error messages<br />ERR_LICENSE=License error messages<br />ERR_CERTIFICATE=Certificate error messages<br />ERR_GROUP=Group error messages<br />ERR_FILE=File-related error messages<br />ERR_LIVEUPDATE=LiveUpdate error messages<br />ERR_OTHER=Other error messages<br />ERR_NONE=None</td>
</tr>
<tr class='even'>
 <td class='detail'>ENFORCERLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated Enforcer names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>ENFORCER_TYPE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>0 = Gateway Enforcer<br />1 = LAN Enforcer<br />2 = DHCP Enforcer<br />3 = Integrated Enforcer<br />4 = NAP Enforcer<br />5 = Peer-To-Peer Enforcer</td>
</tr>
<tr class='even'>
 <td class='detail'>SERVERGROUPLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma separated, wild-card domain names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>CLIENTGROUPLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma separated, wild-card group names by which to filter.</td>
</tr>
<tr class='even'>
 <td class='detail'>SITELIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-card site names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>PARENTSERVERLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-card server names by which to filter.</td>
</tr>
<tr class='even'>
 <td class='detail'>COMPUTERLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>1024</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-card computer names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>IPADDRESSLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-card IP addresses by which to filter.</td>
</tr>
<tr class='even'>
 <td class='detail'>USERLIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-card user names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>POLICYNAMELIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated, wild-card policy names by which to filter.</td>
</tr>
<tr class='even'>
 <td class='detail'>EVENTSOURCELIST</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Comma-separated event names by which to filter.</td>
</tr>
<tr class='odd'>
 <td class='detail'>SORTORDER</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('EVENT_TIME')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The column by which to sort the log views.</td>
</tr>
<tr class='even'>
 <td class='detail'>SORTDIR</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>5</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('DESC')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Sort direction: DESC = Descending, ASC = Ascending</td>
</tr>
<tr class='odd'>
 <td class='detail'>LIMITROWS</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((20))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The number of rows to use for pagination.</td>
</tr>
<tr class='even'>
 <td class='detail'>USERELATIVE</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>2</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('on')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Use relative dates ('on'), or absolute dates.</td>
</tr>
<tr class='odd'>
 <td class='detail'>REPORT_IDX</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('0')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used.</td>
</tr>
<tr class='even'>
 <td class='detail'>REPORTINPUTS</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>128</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Special parameters, if the report needs them.</td>
</tr>
<tr class='odd'>
 <td class='detail'>USN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>A USN-based serial number; this ID is not unique.</td>
</tr>
<tr class='even'>
 <td class='detail'>TIME_STAMP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time on the server when the event is logged into the system (GMT).</td>
</tr>
<tr class='odd'>
 <td class='detail'>DELETED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The deleted flag of the schema object:<br />0 = Deleted<br />1 = Not deleted</td>
</tr>
</table>
<p title='31 columns'>Analyzed at Wed Apr 12 14:15 PDT 2017<p/>
</td></tr></table>
<div class='indent'>
<b>Indexes:</b>
<table class='dataTable' border='1' rules='groups'><colgroup><colgroup><colgroup><colgroup>
<thead>
 <tr>
  <th>Column(s)</th>
  <th>Type</th>
  <th>Sort</th>
  <th class='constraint' style='text-align:left;'>Constraint Name</th>
 </tr>
</thead>
<tbody>
 <tr>
  <td class='primaryKey'>USER_ID + FILTERNAME + SYSTEM_TYPE</td>
  <td class='detail'>Primary key</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>PK_SYSTEMREPORT</td>
 </tr>
</table>
</div>
</div>
</body>
</html>
