<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - Table sem5.dbo.ALERTS</title>
  <link rel=stylesheet href='../schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    table='ALERTS';
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='../index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='../relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='../constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='../anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='../columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>Table <span title='Database'>sem5</span>.<span title='Schema'>dbo</span>.<span title='Table'>ALERTS</span></span><div style='padding: 0px 4px;'>Keeps the risk and Proactive Threat Protection (TruScan) events.</div><p>
</td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%' border='0'>
<tr valign='top'><td class='container' align='left' valign='top'>
<form name='options' action=''>
 <label for='showRelatedCols'><input type=checkbox id='showRelatedCols'>Related columns</label>
 <label for='showConstNames'><input type=checkbox id='showConstNames'>Constraints</label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
 <label for='showLegend'><input type=checkbox checked id='showLegend'>Legend</label>
</form>
</td><td class='container' rowspan='2' align='right' valign='top'>
 <table class='legend' border='0'>
  <tr>
   <td class='dataTable' valign='bottom'>Legend:</td>
  </tr>
  <tr><td class='container' colspan='2'>
   <table class='dataTable' border='1'>
    <tbody>
    <tr><td class='primaryKey'>Primary key columns</td></tr>
    <tr><td class='indexedColumn'>Columns with indexes</td></tr>
    <tr class='impliedRelationship'><td class='detail'><span class='impliedRelationship'>Implied relationships</span></td></tr>
    <tr><td class='excludedColumn'>Excluded column relationships</td></tr>
    <tr><td class='legendDetail'>&lt; <em>n</em> &gt; number of related tables</td></tr>
   </table>
  </td></tr>
 </table>
&nbsp;
</td><tr valign='top'><td class='container' align='left' valign='top'>
<a name='columns'></a>
<table id='columns' class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th>Column</th>
  <th>Type</th>
  <th>Size</th>
  <th title='Are nulls allowed?'>Nulls</th>
  <th title='Is column automatically updated?'>Auto</th>
  <th title='Default value'>Default</th>
  <th title='Columns in tables that reference this column'><span class='notSortedByColumn'>Children</span></th>
  <th title='Columns in tables that are referenced by this column'><span class='notSortedByColumn'>Parents</span></th>
  <th title='Comments' class='comment'><span class='notSortedByColumn'>Comments</span></th>
</tr>
</thead>
<tbody valign='top'>
<tr class='even'>
 <td class='primaryKey' title='Primary Key'>IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>ALERT_IDX</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to table ALERTMSG</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>COMPUTER_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The foreign key to SEM_COMPUTER.COMPUTER_ID.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>SOURCE</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>50</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Hard-coded English string that is used as a lookup key for scan types:<br />"Scheduled Scan"<br />"Manual Scan"<br />"Real-Time Scan"<br />"Integrity Shield"<br />"Definition downloader"<br />"System"<br />"Startup Scan"<br />"DefWatch"<br />"Manual Quarantine"<br />"Reboot Processing"<br />"Heuristic Scan"</td>
</tr>
<tr class='even'>
 <td class='detail'>VIRUSNAME_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table VIRUS.</td>
</tr>
<tr class='odd'>
 <td class='detail'>NOOFVIRUSES</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Number of events for aggregated event record.  This can be due to client-side aggregation, server-side compression, or both.</td>
</tr>
<tr class='even'>
 <td class='detail'>FILEPATH</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The file path of the attacked file.</td>
</tr>
<tr class='odd'>
 <td class='detail'>DESCRIPTION</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='even'>
 <td class='detail'>ACTUALACTION_IDX</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table ACTUALACTION; this is the action taken on the risk.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>REQUESTEDACTION_IDX</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table ACTUALACTION; this is the action requested by the policy.</td>
</tr>
<tr class='even'>
 <td class='detail'>SECONDARYACTION_IDX</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table ACTUALACTION; this is the secondary action requested by the policy.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>ALERTDATETIME</td>
 <td class='detail'>datetime</td>
 <td class='detail' align='right'>16,3</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('19700101')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time that the event occurred.</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>ALERTINSERTTIME</td>
 <td class='detail'>datetime</td>
 <td class='detail' align='right'>16,3</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('19700101')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time that the event was inserted into the database.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>SERVERGROUP_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table IDENTITY_MAP; this is the SEPM domain GUID.</td>
</tr>
<tr class='even'>
 <td class='detail'>USER_NAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>128</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The user that was logged into the computer when the event took place.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>PARENTSERVER_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table IDENTITY_MAP; this is the SEPM server GUID.</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>CLIENTGROUP_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table IDENTITY_MAP; this is the SEPM group GUID.</td>
</tr>
<tr class='odd'>
 <td class='detail'>SOURCE_COMPUTER_NAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>128</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>This is the source of the threat. This is logged when Risk Tracer is enabled in the Virus and Spyware Protection policy.</td>
</tr>
<tr class='even'>
 <td class='detail'>SOURCE_COMPUTER_IP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>This is the source of the threat. This is logged when Risk Tracer is enabled in the Virus and Spyware Protection policy.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>MOTHER_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the related compressed event in the ALERTS table. This is the compressed event created by database maintenance. A value here means this event has been aggregated on the server-side and is a child event.</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>LAST_LOG_SESSION_GUID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>This is an ID used by the client to keep track of related threat events.</td>
</tr>
<tr class='odd'>
 <td class='detail'>ALERTENDDATETIME</td>
 <td class='detail'>datetime</td>
 <td class='detail' align='right'>16,3</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('19700101')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Time at which event ended.  This is the end of the aggregated event time.</td>
</tr>
<tr class='even'>
 <td class='detail'>HPP_APP_IDX</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table HPP_APPLICATION.</td>
</tr>
<tr class='odd'>
 <td class='detail'>SITE_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table IDENTITY_MAP; this is the SEPM site GUID.</td>
</tr>
<tr class='even'>
 <td class='detail'>VBIN_ID</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Client-side ID of the quarantined threat, if quarantined.</td>
</tr>
<tr class='odd'>
 <td class='detail'>SCAN_ID</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the scan table event that picked up this event.</td>
</tr>
<tr class='even'>
 <td class='detail'>USN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>A USN-based serial number; this ID is not unique.</td>
</tr>
<tr class='odd'>
 <td class='detail'>TIME_STAMP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time on the server when the event is logged into the system or updated in the system (GMT).</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>DELETED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Deleted row: 0 = not deleted, 1 = deleted</td>
</tr>
<tr class='odd'>
 <td class='detail'>LOCAL_HOST_IP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The IP address of the local host.</td>
</tr>
<tr class='even'>
 <td class='detail'>AV_PRODUCT</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>256</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The antivirus product name.</td>
</tr>
<tr class='odd'>
 <td class='detail'>AV_PRODUCT_VERSION</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>64</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Antivirus product version.</td>
</tr>
<tr class='even'>
 <td class='detail'>STATUS</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>6</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>SCAN_GUID_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
</table>
<p title='34 columns'>Analyzed at Wed Apr 12 14:15 PDT 2017<p/>
</td></tr></table>
<div class='indent'>
<b>Indexes:</b>
<table class='dataTable' border='1' rules='groups'><colgroup><colgroup><colgroup><colgroup>
<thead>
 <tr>
  <th>Column(s)</th>
  <th>Type</th>
  <th>Sort</th>
  <th class='constraint' style='text-align:left;'>Constraint Name</th>
 </tr>
</thead>
<tbody>
 <tr>
  <td class='primaryKey'>IDX</td>
  <td class='detail'>Primary key</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>PK_ALERTS</td>
 </tr>
 <tr>
  <td class='indexedColumn'>ALERTINSERTTIME</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_ALERTS_ALERTINSERTTIME</td>
 </tr>
 <tr>
  <td class='indexedColumn'>CLIENTGROUP_IDX</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_ALERTS_CLIENTGROUP_IDX</td>
 </tr>
 <tr>
  <td class='indexedColumn'>LAST_LOG_SESSION_GUID</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_ALERTS_LAST_LOG_SESSION_GUID_PLUS</td>
 </tr>
 <tr>
  <td class='indexedColumn'>PARENTSERVER_IDX</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_ALERTS_PARENTSERVER_IDX</td>
 </tr>
 <tr>
  <td class='indexedColumn'>REQUESTEDACTION_IDX</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_ALERTS_REQUESTEDACTION_IDX</td>
 </tr>
 <tr>
  <td class='indexedColumn'>SERVERGROUP_IDX</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_ALERTS_SERVERGROUP_IDX</td>
 </tr>
 <tr>
  <td class='indexedColumn'>ALERTDATETIME + COMPUTER_IDX + MOTHER_IDX + SOURCE + ALERT_IDX + DELETED</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_ALERTS_SOURCE_ALERT_IDX</td>
 </tr>
</table>
</div>
</div>
</body>
</html>
