<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - Table sem5.dbo.SERVER_SYSTEM_LOG_1</title>
  <link rel=stylesheet href='../schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    table='SERVER_SYSTEM_LOG_1';
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='../index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='../relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='../constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='../anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='../columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>Table <span title='Database'>sem5</span>.<span title='Schema'>dbo</span>.<span title='Table'>SERVER_SYSTEM_LOG_1</span></span><div style='padding: 0px 4px;'>Keeps system activities that occur in server.</div><p>
</td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%' border='0'>
<tr valign='top'><td class='container' align='left' valign='top'>
<form name='options' action=''>
 <label for='showRelatedCols'><input type=checkbox id='showRelatedCols'>Related columns</label>
 <label for='showConstNames'><input type=checkbox id='showConstNames'>Constraints</label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
 <label for='showLegend'><input type=checkbox checked id='showLegend'>Legend</label>
</form>
</td><td class='container' rowspan='2' align='right' valign='top'>
 <table class='legend' border='0'>
  <tr>
   <td class='dataTable' valign='bottom'>Legend:</td>
  </tr>
  <tr><td class='container' colspan='2'>
   <table class='dataTable' border='1'>
    <tbody>
    <tr><td class='primaryKey'>Primary key columns</td></tr>
    <tr><td class='indexedColumn'>Columns with indexes</td></tr>
    <tr class='impliedRelationship'><td class='detail'><span class='impliedRelationship'>Implied relationships</span></td></tr>
    <tr><td class='excludedColumn'>Excluded column relationships</td></tr>
    <tr><td class='legendDetail'>&lt; <em>n</em> &gt; number of related tables</td></tr>
   </table>
  </td></tr>
 </table>
&nbsp;
</td><tr valign='top'><td class='container' align='left' valign='top'>
<a name='columns'></a>
<table id='columns' class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th>Column</th>
  <th>Type</th>
  <th>Size</th>
  <th title='Are nulls allowed?'>Nulls</th>
  <th title='Is column automatically updated?'>Auto</th>
  <th title='Default value'>Default</th>
  <th title='Columns in tables that reference this column'><span class='notSortedByColumn'>Children</span></th>
  <th title='Columns in tables that are referenced by this column'><span class='notSortedByColumn'>Parents</span></th>
  <th title='Comments' class='comment'><span class='notSortedByColumn'>Comments</span></th>
</tr>
</thead>
<tbody valign='top'>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>USN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>A USN-based serial number; this ID is not unique.</td>
</tr>
<tr class='even'>
 <td class='detail'>DOMAIN_ID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Not used; logged as ''.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>SITE_ID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The GUID of the site to which the log belongs.</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>SERVER_ID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The GUID of the server to which the log belongs.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>TIME_STAMP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time on the server when the event is logged into the system (GMT).</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>SEVERITY</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The severity, which can be one of the following: SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST.<br />>= 400 is FINER and above.<br />>=500 is FINE and above.<br />>=700 is CONFIG and above.<br />>=800 is INFO and above.<br />>=900 is WARNING and above.<br />>=1000 is SEVERE and above.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>EVENT_ID</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The unique ID for the system event.<br /><br /> Server events; possible values are as follows:<br /> 257 = The management server started up successfully.<br /> 258 = The management server startup failed.<br /> 259 = The management server shut down gracefully.<br /> 260 = The management server was created.<br /> 261 = The site was created.<br /> 262 = The package was published.<br /> 263 = The site license was exceeded.<br /> 264 = The import of an Organizational Unit or Container started.<br /> 265 = The import of the Organizational Unit or Container succeeded.<br /> 266 = The import of the Organization Unit or Container failed.<br /> 267 = The client sweeping task started.<br /> 268 = The client sweeping task summary.<br /> 269 = The client sweeping task succeeded.<br /> 270 = The client sweeping task failed.<br /> 271 = The database logs have been swept.<br /> 272 = The management server upgrade was successful.<br /> 273 = Scheduled reporting failed.<br /> 274 = The virus definitions folder does not exist.<br /> 275 = The process {0} cannot lock the process status table. The process status has been locked by the server {1} since {2}.<br /> 276 = Whitelist and Blacklist LiveUpdate.<br /> 281 = The resource is locked.<br /> <br /> Replication events; possible values are as follows:<br /> 769 = Replication from a remote site started.<br /> 770 = Replication failed to log on to remote site.<br /> 771 = Unable to fetch changed data from the remote site.<br /> 772 = Replication finished successfully.<br /> 773 = Replication failed.<br /> 774 = Replication merge failed.<br /> 775 = Unable to connect to the remote site.<br /> 776 = Name changed to resolve merge conflict.<br /> 777 = The group full path name is too long for replication.<br /> 778 = Retrieval of local changed data for remote site started.<br /> 779 = Retrieval of local changed data for remote site finished successfully.<br /> 780 = Retrieval of local changed data for remote site failed.<br /> 781 = Replication has been chosen as the deadlock victim and has been killed by the database.<br /> 782 = Replication data has been received.<br /> 783 = The database versions do not match between local and remote sites.<br /> <br /> Backup events; possible values are as follows:<br /> 1025 = The backup connection failed.<br /> 1026 = The backup data fetch failed.<br /> 1027 = The backup file write failed.<br /> 1028 = The backup failed.<br /> 1029 = The backup succeeded.<br /> 1030 = The backup started.<br /> <br /> System error events; possible values are as follows:<br /> 1281 = An unexpected exception occurred.<br /> 1282 = The connection to the mail server failed.<br /> 1283 = Failed to start the RADIUS Server. The RADIUS port may be in use by another process.<br /> 1284 = Failed to start the RADIUS Server. Set Non-block I/O Socket failed.<br /> 1285 = Failed to start the RADIUS Server. Create Socket error.<br /> 1286 = Server error.<br /> <br /> Policy events; possible values are as follows:<br /> 1537 = Added the intrusion prevention policy.<br /> 1538 = Deleted the intrusion prevention policy.<br /> 1539 = Updated the intrusion prevention policy.<br /> 1540 = The intrusion prevention policy is up to date.<br /> 1541 = Skipped publishing a content revision during a LiveUpdate content policy compilation, as the corresponding binary file exists.<br /> <br /> LiveUpdate events; possible values are as follows:<br /> 1793 = LiveUpdate started.<br /> 1794 = LiveUpdate succeeded.<br /> 1795 = LiveUpdate failed.<br /> 1796 = The manual launch of LiveUpdate succeeded.<br /> 1797 = The manual launch of LiveUpdate failed.<br /> 1798 = The LiveUpdate retry started.<br /> 1799 = The LiveUpdate retry succeeded.<br /> 1800 = The LiveUpdate retry failed.<br /> 1802 = The download started.<br /> 1803 = The retry timestamp is over the maximum retry window; switching to the regular schedule run.<br /> 1804 = The LiveUpdate retry failed, but will try again.<br /> 1805 = The retry timestamp is equal to or after the next schedule time; switching to the regular schedule run.<br /> 1806 = LUALL.EXE has been launched.<br /> 1807 = LUALL.EXE exited abnormally.<br /> 1808 = LUALL.EXE finished running.<br /> 1809 = LUALL.EXE failed.<br /> 1810 = Started uploading content to the database.<br /> 1811 = The specified LiveUpdate file path does not exist.<br /> 1812 = The LiveUpdate content category file has been inserted.<br /> 1813 = The LiveUpdate content category file has been updated.<br /> 1814 = The client package has been downloaded.<br /> 1815 = The client package patching failed.<br /> 1816 = New LiveUpdate content has been downloaded.<br /> 1817 = There is an error in the LiveUpdate upload URL parameters.<br /> 1818 = Failed to download the LiveUpdate content.<br /> 1819 = Cleaned up the LiveUpdate downloaded content.<br /> 1820 = The Host Integrity template has been updated.<br /> 1821 = LiveUpdate exceeded its timeout. The process is destroyed.<br /> 1822 = LiveUpdate next start time and server.<br /> 1824 = Failed to update.<br /> 1825 = {0} is up-to-date.<br /> 1826 = LiveUpdate re-run is triggered by content catalog update.<br /> 1827 = {0} is not available on the LiveUpdate server.<br /> 1828 = The Manual LiveUpdate cancelled.<br /> 1829 = LiveUpdate was delayed.<br /> <br /> Network Audit events; possible values are as follows:<br /> 2049 = The Network Audit Search Unagented Hosts was started.<br /> 2050 = The Network Audit Search Unagented Hosts finished normally.<br /> 2051 = The Network Audit Search Unagented Hosts finished abnormally.<br /> 2052 = The Network Audit Client Remote Pushing Install started.<br /> 2053 = The Network Audit Client Remote Pushing Install finished normally.<br /> 2054 = Network Audit Client Remote Pushing Install finished abnormally.<br /> <br /> Rapid Response content events; possible values are as follows:<br /> 2305 = Rapid Response content installed successfully.<br /> 2306 = Rapid Response content failed to install.<br /> <br /> Certificate events; possible values are as follows:<br /> 4097 = Got a valid certificate.<br /> 4098 = Got a mismatched certificate.<br /> <br /> JDNI events; possible values are as follows:<br /> 4353 = Management server has detected and ignored one or more duplicate entries. Please check the following entries in your directory server:\n{0}.<br /> <br /> Send email events; possible values are as follows:<br /> 4609 = Failed to send email.<br /> 4610 = Failed to send email directly to mail server.<br /> <br /> Licensing events; possible values are as follows:<br /> 4865 = Add a license.<br /> 4866 = Renew a license.<br /> 4867 = Delete a license.<br /> 4868 = Import a trial license.<br /> 4869 = Import an upgrade license.<br /> 4870 = The license has expired.<br /> 4871 = The license has been overdeployed.<br /> 4872 = Removed trial license.<br /> <br /> Transaction log truncation events; possible values are as follows:<br /> 5121 = The Truncate Transaction Log Task started.<br /> 5122 = The Truncate Transaction Log Task succeeded.<br /> 5123 = The Truncate Transaction Log Task failed.<br /> <br /> Rebuild indexes events; possible values are as follows:<br /> 5377 = The Rebuild Indexes Task started.<br /> 5378 = Rebuild Indexes Task succeeded.<br /> 5379 = Rebuild Indexes Task failed.<br /> <br /></td>
</tr>
<tr class='even'>
 <td class='detail'>EVENT_DESC</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>4000</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Description of the event. Usually, the first line of the description is treated as the summary.</td>
</tr>
<tr class='odd'>
 <td class='detail'>MSG_ID</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The event description ID. Use this ID to load a localized message (only used when an exception is related to this event). <br /><br />MSG IDs:<br /><br />ERROR_MSG_x1 = Unexpected server error.<br />ERROR_MSG_x2 = Unexpected console error.<br />ERROR_MSG_x3 = Failed to connect to the server. Make sure that the server is running and your session has not timed out. If you can reach the server but cannot log on, make sure that you provided the correct parameters. If you are experiencing network issues, contact your system administrator.<br />ERROR_MSG_x4 = Unknown response.<br />ERROR_MSG_x5 = No response code.<br />ERROR_MSG_x6 = Invalid response code.<br />ERROR_MSG_x7 = You are no longer connected to the Symantec Endpoint Protection Manager. You must log on again to continue.<br />ERROR_MSG_x8 = Logon failed.<br />ERROR_MSG_x9 = Invalid action.<br />ERROR_MSG_xA = Unable to connect to the database.<br />ERROR_MSG_xB = Invalid parameter.<br />ERROR_MSG_xC = Administrator name is already in use.<br />ERROR_MSG_xD = Administrator not found.<br />ERROR_MSG_xE = Group not found.<br />ERROR_MSG_xF = Invalid response data.<br />ERROR_MSG_x10 = Site not found.<br />ERROR_MSG_x11 = Query not found.<br />ERROR_MSG_x12 = The results returned are more than 100 records.<br />ERROR_MSG_x13 = Only select query is allowed.<br />ERROR_MSG_x14 = Invalid query statement.<br />ERROR_MSG_x15 = The data type you selected is not supported.<br />ERROR_MSG_x16 = You cannot delete all the administrators.<br />ERROR_MSG_x17 = The action type is null.<br />ERROR_MSG_x18 = The action type is invalid.<br />ERROR_MSG_x19 = The object GUID is null.<br />ERROR_MSG_x1A = The object GUID is invalid.<br />ERROR_MSG_x1B = The transaction GUID is null.<br />ERROR_MSG_x1C = The transaction GUID is invalid.<br />ERROR_MSG_x1D = The domain GUID is null.<br />ERROR_MSG_x1E = The domain GUID is invalid.<br />ERROR_MSG_x1F = The object type is null.<br />ERROR_MSG_x20 = The object type is invalid.<br />ERROR_MSG_x21 = There is no connection.<br />ERROR_MSG_x22 = The connection is invalid.<br />ERROR_MSG_x23 = The file fingerprint is null.<br />ERROR_MSG_x24 = The policy update is invalid.<br />ERROR_MSG_x25 = Request is invalid.<br />ERROR_MSG_x26 = The SQL query is null.<br />ERROR_MSG_x27 = The USN is null.<br />ERROR_MSG_x28 = The USN is invalid.<br />ERROR_MSG_x29 = This method with a domain parameter can only called by System Administrators.<br />ERROR_MSG_x2A = Invalid SQL query type.<br />ERROR_MSG_x2B = Invalid SQL query parameter.<br />ERROR_MSG_x2C = The administrator's user name or password is incorrect. Enter a valid user name and password.<br />ERROR_MSG_x2D = Domain is disabled.<br />ERROR_MSG_x2E = The administrator account has no access.<br />ERROR_MSG_x2F = The administrator account is locked.<br />ERROR_MSG_x30 = Domain not found.<br />ERROR_MSG_x31 = The management server does not support RSA SecurID logon.<br />ERROR_MSG_x32 = The transaction does not exist.<br />ERROR_MSG_x33 = The transaction rollback failed.<br />ERROR_MSG_x34 = The transaction commit failed.<br />ERROR_MSG_x35 = The transaction start failed.<br />ERROR_MSG_x36 = The object cannot be found.<br />ERROR_MSG_x37 = The object's content is corrupt.<br />ERROR_MSG_x38 = The object is concurrently updating.<br />ERROR_MSG_x39 = The datastore is not connected.<br />ERROR_MSG_x3A = Datastore error.<br />ERROR_MSG_x3B = The target site belongs to a different group of sites.<br />ERROR_MSG_x3C = The top level group cannot be deleted.<br />ERROR_MSG_x3D = Unable to delete this group because there are still clients or subgroups in the group.<br />ERROR_MSG_x3E = Unable to delete this group because there are still clients in the group.<br />ERROR_MSG_x40 = The license has expired.<br />ERROR_MSG_x41 = You have reached the limit of your license.<br />ERROR_MSG_x42 = Your license doesn't support this feature.<br />ERROR_MSG_x43 = Invalid Site License.<br />ERROR_MSG_x44 = You cannot access this server from this IP address.<br />ERROR_MSG_x45 = Invalid certificate file.<br />ERROR_MSG_x46 = Invalid private key file.<br />ERROR_MSG_x47 = Invalid keystore file.<br />ERROR_MSG_x48 = Invalid keystore password.<br />ERROR_MSG_x49 = Failed to write certificate on server.<br />ERROR_MSG_x4A = The length of an administrator name must be between {0} and {1} characters.<br />ERROR_MSG_x4B = The administrator name cannot contain any one of {0} characters.<br />ERROR_MSG_x4C = The administrator name should not be all dots or spaces.<br />ERROR_MSG_x4D = An Active Directory node cannot be moved.<br />ERROR_MSG_x4E = The global or temporary groups cannot be moved.<br />ERROR_MSG_x4F = The group cannot be moved to any Active Directory node.<br />ERROR_MSG_x50 = The group cannot be moved to the temporary group.<br />ERROR_MSG_x51 = The Organizational Unit is already in use.<br />ERROR_MSG_x52 = You must enter a hostname.<br />ERROR_MSG_x53 = Failed to connect to the directory server.<br />ERROR_MSG_x54 = Failed to read {0}.<br />ERROR_MSG_x55 = The action is null.<br />ERROR_MSG_x56 = The restore file is invalid.<br />ERROR_MSG_x57 = Failed to create a folder to which to publish the package.<br />ERROR_MSG_x58 = You cannot use the same site name as a remote replication site.<br />ERROR_MSG_x59 = The {0} group was not found.<br />ERROR_MSG_x5A = The group path is not valid.<br />ERROR_MSG_x5B = The partner is not found.<br />ERROR_MSG_x5C = The name is a duplicate.<br />ERROR_MSG_x5D = A site referenced by the installation instance was not found.<br />ERROR_MSG_x5E = The local site seems to have been deleted from the installation instance.<br />ERROR_MSG_x5F = The Organizational Unit group ID is invalid.<br />ERROR_MSG_x60 = The domain ID is invalid in the session when trying to import the Organizational Unit.<br />ERROR_MSG_x61 = The destination group is same as the source group.<br />ERROR_MSG_x62 = The URL you specified is not accessible. This may be caused by network connection problems, or the web site is down.<br />ERROR_MSG_x63 = The management server is running another process. Check the server system log for details.<br />ERROR_MSG_x64 = Invalid key password.<br />ERROR_MSG_x65 = Browse Network Error. Make sure that the Computer Browser service in Windows is started and running.<br />ERROR_MSG_x70 = The domain name is already in use.<br />ERROR_MSG_x71 = The management server can only query users from the domains it belongs to.<br />ERROR_MSG_x72 = The management server can only filter users from the domains it belongs to.<br />ERROR_MSG_x73 = The administrator account does not have permission to perform the requested task.<br />ERROR_MSG_x74 = Your hard disk {0} space is less than {1}MB and impacts the performance of Symantec Endpoint Protection Manager. You should delete some files to free up space. Symantec recommends that you have a minimum of {2}GB of free disk space.<br />ERROR_MSG_x75 = Your hard disk {0} space is less than {1}MB. Symantec Endpoint Protection Manager requires more disk space to complete certain tasks. Please delete some files to free up some space. Symantec recommends that you have a minimum of {2}GB of free disk space.<br />ERROR_MSG_x80 = The group full name is too long.<br />ERROR_MSG_x81 = Failed to resolve naming conflict.<br />ERROR_MSG_x82 = No response from the remote server.<br />ERROR_MSG_x83 = Email sending failed.<br />ERROR_MSG_x84 = Failed to check duplicate names.<br />ERROR_MSG_x85 = The legacy client is not found.<br />ERROR_MSG_x86 = The file is not found.<br />ERROR_MSG_x87 = An IO exception occurred.<br />ERROR_MSG_x88 = There were one or more errors when parsing the file from the client.<br />ERROR_MSG_x89 = A validation exception occurred.<br />ERROR_MSG_x90 = Unexpected parameter value.<br />ERROR_MSG_x91 = Missing named version.<br />ERROR_MSG_x92 = Missing PackageLuInfo.<br />ERROR_MSG_x93 = Missing LuCatalog File.<br />ERROR_MSG_x94 = Missing LuContentPolicy.<br />ERROR_MSG_x95 = Symantec Endpoint Protection Manager could not connect to the target directory server. Check the directory server configuration, and try again.<br />ERROR_MSG_x96 = Failed to connect to the specified replication partner server. Verify that the server name and port are correct.<br />ERROR_MSG_x97 = Invalid Syslog server name.<br />ERROR_MSG_x98 = The management server has detected and ignored one or more invalid or duplicate entries. Check the following entries in your directory server:<br />ERROR_MSG_x99 = Domain has been disabled.<br />ERROR_MSG_x9A = The replication partner does not run the same version as the local site.<br />ERROR_MSG_x9B = You cannot log on to the console because the server is not synchronized with the database. Upgrade the server, and then log on to the console.<br />ERROR_MSG_x9C = The replicated software package cannot be found in the cache.<br />ERROR_MSG_x9D = Remote site [{0}] is downloading LiveUpdate contents and cannot prepare the data until the next round of replication.<br />ERROR_MSG_x9E = Remote site [{0}] failed to prepare the data for replication.<br />ERROR_MSG_x9F = Remote site {0} blocks new clients. The client cannot register with remote site {0}.<br />ERROR_MSG_xA0 = Failed to connect to {0}. Make sure the server can ping or resolve this domain.<br />ERROR_MSG_xA1 = Unable to load binary file.<br />ERROR_MSG_xA2 = Error occurred during unzip operation.<br />ERROR_MSG_xA3 = Unable to load group profile.<br />ERROR_MSG_xA4 = Unable to generate packlist file.<br />ERROR_MSG_xA5 = Unable to modify config.xml.<br />ERROR_MSG_xA6 = Unable to modify setAid.ini file.<br />ERROR_MSG_xA7 = Unable to generate single .exe.<br />ERROR_MSG_xA8 = Unable to query database.<br />ERROR_MSG_xA9 = Unable to load server list.<br />ERROR_MSG_xAA = Unable to load software package data.<br />ERROR_MSG_xAF = Not enough disk space on the server. Cannot continue.<br />ERROR_MSG_xB0 = Your temporary password could not be activated. Make sure that the account for which you requested a password is valid and try again.<br />ERROR_MSG_xB1 = You must use the most recent link that you were sent to reset your password. If the link does not work, copy the link from the email and paste it into your browser address bar.<br />ERROR_MSG_xB2 = Domain not found.<br />ERROR_MSG_xB3 = No email account associated with that logon.<br />ERROR_MSG_xB4 = The server cannot send the email message to the administrator. Check that the email server is connected, or that the email address (and email credentials) for this administrator are correct.<br />ERROR_MSG_xB5 = Invalid administrator name.<br />ERROR_MSG_xB6 = Reset password failed.<br />ERROR_MSG_xB7 = Email server has not been configured yet.<br />ERROR_MSG_xB8 = You do not have permission to reset the administrator password. Contact the system administrator at this site to enable the reset password option.<br />ERROR_MSG_xB9 = Server failed to generate a random password.<br />ERROR_MSG_xBA = You must wait five minutes before you can request another temporary password.<br />ERROR_MSG_xBB = The URL to activate this password is incorrect. Copy and paste the URL from the email message again.<br />ERROR_MSG_xBC = You have successfully activated your password reset request. You can now use the new password to log on to Symantec Endpoint Protection Manager.<br />ERROR_MSG_xBD = Your password reset link has expired. You must use the link within eight hours of receiving it. To reset your password, click "Forgot your password?" in the Symantec Endpoint Protection Manager console logon window.<br />ERROR_MSG_xBE = Unable to process password reset request. A valid IP address for the Symantec Endpoint Protection Manager was not found. Please select or enter a valid IP address and try again.<br />ERROR_MSG_xBF = The password cannot be reset because your authentication mode is not set to Symantec Endpoint Protection Manager authentication. Any Symantec Endpoint Protection administrator can change your password.<br />ERROR_MSG_xC0 = The parameters that were passed for the network scan are invalid.<br />ERROR_MSG_xC1 = The user cancelled the network scan.<br />ERROR_MSG_xC2 = The network scan timed out. Try to run the scan again.<br />ERROR_MSG_xC3 = The network scan could not be completed because the .dlls+A192 for Windows ICMP ping could not be found.<br />ERROR_MSG_xC4 = The network scan could not be completed because the auditparams.txt file is invalid or missing.<br />ERROR_MSG_xC5 = The network scan could not be completed because of an unknown error. Try to run the scan again later.<br />ERROR_MSG_xC6 = The network scan timed out for some of the target IP addresses.<br />ERROR_MSG_xC7 = Unable to load package data. Cannot continue.<br />ERROR_MSG_xC8 = Not enough disk space on the server. Cannot continue.<br />ERROR_MSG_xC9 = Failed to copy Host Integrity (HI) Content Library to install packages.<br />ERROR_MSG_xCA = The logon response from the remote partner is null.<br />ERROR_MSG_xCB = License information from the remote server is not available.<br />ERROR_MSG_xCC = The server schema version on the local server is newer than the server schema version of the replication partner on the remote site.  Please upgrade the remote server to ensure that the versions match.<br />ERROR_MSG_xCD = License information from the remote server is not available.<br />ERROR_MSG_xCE = The server schema version on the local server is older than the server schema version of the replication partner on the remote site.  Please upgrade the local server to ensure that the versions match.<br />ERROR_MSG_xCF = Remote server is not an Enterprise Server.<br />ERROR_MSG_xD0 = Replication partnership has been deleted from remote site.<br />ERROR_MSG_xD1 = Replication partnership has been setup between this site and remote site.<br />ERROR_MSG_xD2 = Invalid password for replication partnership logon.<br />ERROR_MSG_xD3 = Copy license file to install packages failed.<br />ERROR_MSG_xD4 = The time difference between the local site and the remote site is more than 10 minutes. Please synchronize server times to ensure correct replication of data.<br />ERROR_MSG_xD5 = The export folder path is too long. This is probably because the installation path for Symantec Endpoint Protection Manager is too long.<br />ERROR_MSG_xD6 = Unable to generate a package in .zip format.<br />ERROR_MSG_xE1 = Invalid administrator name.<br />ERROR_MSG_xE2 = An error occurred while verifying the signature of your ticket. Contact the administrator to resolve this issue.<br />ERROR_MSG_xE3 = The ticket signature from a certificate keystore is invalid. Contact the administrator to rectify this issue.<br />ERROR_MSG_xE4 = The signed data length received on the ticket is invalid. Contact the administrator to rectify this issue.<br />ERROR_MSG_xE5 = Ticket version not supported by current Symantec Endpoint Protection installation. Contact the administrator to rectify this issue.<br />ERROR_MSG_xE6 = The issue date for the ticket is invalid. Check that system times for the two servers are synchronized.<br />ERROR_MSG_xE7 = The logon ticket is expired. This can be due to timing differences in servers or an expired ticket being used for logon. Contact the administrator.<br />ERROR_MSG_xE8 = The Symantec Endpoint Protection domain you are trying to access is currently disabled.<br />ERROR_MSG_xE9 = The username used for logon is invalid. Contact the administrator to verify that the Symantec Endpoint Protection account associated with your account is valid.<br />ERROR_MSG_xEA = Cannot add root.<br />ERROR_MSG_xEB = Cannot delete root.<br />ERROR_MSG_xEC = The Symantec Endpoint Protection domain used for logon is invalid. Contact the administrator to verify that the Symantec Endpoint Protection domain associated with your account is valid.<br />ERROR_MSG_xED = The product you are trying to access is not registered. Contact the administrator to verify the registration with the required Symantec Endpoint Protection server.<br />ERROR_MSG_xEE = An error occurred while validating the ticket for your logon request. Try logging on again and if the error persists, contact the administrator.<br />ERROR_MSG_xEF = The specified user credentials cannot be used to logon for the current registration. Contact the administrator to update your Symantec Endpoint Protection account mapping.<br />ERROR_MSG_xF1 = LiveUpdate failed.<br />ERROR_MSG_xF2 = The new password must be different from the old password. Try again.<br />ERROR_MSG_xF3 = The version of Symantec Endpoint Protection Manager that you are trying to run is not the same as the version you are trying to connect to. This situation can occur between replication partners, or between the remote console and the management server. Upgrade any replication partners, or download the correct version of the remote console from the management server.<br />ERROR_MSG_xF4 = Email sending directly to the mail server failed.<br />ERROR_MSG_xF5 = The latest contents are missing.<br />ERROR_MSG_xF6 = The latest contents are missing.<br />ERROR_MSG_xF7 = An error occurred while validating the certificate for your logon request. Please try logging on again and if the error persists, contact the administrator.<br />ERROR_MSG_xF8 = Create domain failed. The specified domain ID is already in use. Choose another domain ID.<br />ERROR_MSG_xF9 = LDAP Authentication Failed [path={0}, user={1}]. It may fail due to an invalid account name or password, or the account is currently locked out by domain security policy.<br />ERROR_MSG_xFA = Your server certificate is not validated. If you trust the server, you must accept the certificate. Log in again and if the error persists, contact your administrator.<br />ERROR_MSG_xFB = Your command is already entered to be sent to your some of the clients. See the log file for details. Your command will be sent to the client shortly. Check the Command Status on the Monitors page to see the progress of your command.<br />ERROR_MSG_xFC = Your command is already entered to be sent to your clients. No new entries added. See log file for details. Your command will be sent to the client shortly. Check the Command Status on the Monitors page to see the progress of your command.<br />ERROR_MSG_xFD = You must enable at least one domain before you can log on to the Symantec Endpoint Protection Manager console.<br />ERROR_MSG_xFE = You must create a domain before you can log on to the Symantec Endpoint Protection Manager console.<br />ERROR_MSG_xFF = You are not authorized to execute this request.<br />ERROR_MSG_x100 = Request could not be authorized.<br />ERROR_MSG_x101 = Only system administrator account is allowed.<br />ERROR_MSG_x102 = Could not log on to the server because of a hostname mismatch. Learn more at http://www.symantec.com/docs/TECH205165<br />ERROR_MSG_x103 = Could not browse the network. The Bonjour service is missing. For more information, see the Technical Support article for installing the Bonjour service (http://www.symantec.com/docs/TECH213283).<br />ERROR_MSG_x104 = Could not browse the network. The Bonjour service is stopped. For more information, see the Technical Support article for installing the Bonjour service (http://www.symantec.com/docs/TECH213283).<br />ERROR_MSG_x105 = Failed to confirm the server certificate before the request timed out.<br />ERROR_MSG_x106 = The specified file is not a valid known_hosts file. Choose a valid file and try again.<br />ERROR_MSG_x107 = The host key for host {0} does not match. Verify the identity of the host or provide an updated known_hosts file and try again.<br />ERROR_MSG_x108 = The host {0} could not be found in the specified file. Remove the host from the list or provide an updated file that contains the correct host information and try again.<br />ERROR_MSG_x109 = An unknown error occurred while validating the host {0} against the specified file.<br />ERROR_MSG_x10A = The setting cannot be updated. This error might occur because the setting was already modified by another administrator. Refresh the management console and try to modify the setting again. If the error persists, a system administrator should run the Database Validation tool to confirm that the database passes a validation check.<br />ERROR_MSG_x10B = Password verification threshold exceeded.<br />ERROR_MSG_x200 = Failed to synchronize with the directory server {0}. Check the directory server settings in the management console and try again.<br /><br />Error message buckets as used in the SYSTEM_REPORT table, field MSG_ID:<br />ERR_SERVER' = array('9', 'A', 'B', 'C', 'D', 'E', 'F', '10', '11', '12', '13', '14', '15', '16');<br />ERR_INVALID_PARAMETER' = array('17', '18', '19', '1A', '1B', '1C', '1D', '1E', '1F', '20', '21', '22', '23', '24');<br />ERR_GENERAL' = array('1','2','3','4','5','6','7','8');<br />ERR_ROOT' = array('2A', '2B');<br />ERR_AUTHENTICATION' = array('2C', '2D', '2E', '2F', '30', '31', '4A', '4B', '4C');<br />ERR_METADATA' = array('36', '37', '38');<br />ERR_TRANSACTION' = array('32', '33', '34', '35');<br />ERR_DATASTORE' = array('39', '3A', '3B');<br />ERR_LICENSE' = array('40', '41', '42', '43');<br />ERR_CERTIFICATE' = array('45', '46', '47', '48', '49');<br />ERR_GROUP' = array('4D', '4E', '4F', '50');<br />ERR_FILE' = array('86','87', '88', '89', '90');<br />ERR_LIVEUPDATE' = array('92','93','94','97');<br />ERR_OTHER' = array('29', '3C', '3D', '44', '54', '57', '58', '59', '5A', '5D', '5E', '5F', '60', '62', '70', '71', '80', '81', '82', '83', '84', '85','91','95','96');<br />ERR_NONE' = array(-1);<br /></td>
</tr>
<tr class='even'>
 <td class='detail'>ERROR_CODE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Can uniquely identify the error in the source code (only used when an exception is related to this event). <br /><br />Error codes:<br />ERROR_CODE_x00000000 = OK<br />ERROR_CODE_x10010000 = Unexpected server error.<br />ERROR_CODE_x10020000 = Failed to connect to Server.<br />ERROR_CODE_x11010000 = Invalid session.<br />ERROR_CODE_x12010000 = The action type is null.<br />ERROR_CODE_x12020000 = The action type is invalid.<br />ERROR_CODE_x12030000 = The object GUID is null.<br />ERROR_CODE_x12040000 = The object GUID is invalid.<br />ERROR_CODE_x12050000 = The transaction GUID is null.<br />ERROR_CODE_x12060000 = The transaction GUID is invalid.<br />ERROR_CODE_x12070000 = The domain GUID is null.<br />ERROR_CODE_x12080000 = The domain GUID is invalid.<br />ERROR_CODE_x12090000 = The object type is null.<br />ERROR_CODE_x120a0000 = The object type is invalid.<br />ERROR_CODE_x120b0000 = There is no connection.<br />ERROR_CODE_x120c0000 = The connection is invalid.<br />ERROR_CODE_x120d0000 = The checksum is null.<br />ERROR_CODE_x120e0000 = The policy update is invalid.<br />ERROR_CODE_x120f0000 = The SQL query is null.<br />ERROR_CODE_x12100000 = The USN is null.<br />ERROR_CODE_x12110000 = The USN is invalid.<br />ERROR_CODE_x12120000 = The request is invalid.<br />ERROR_CODE_x12130000 = This method with a domain parameter can only be called by System Administrators.<br />ERROR_CODE_x12140000 = The action is null.<br />ERROR_CODE_x12150000 = Invalid action.<br />ERROR_CODE_x12160000 = The client registration domain name is null.<br />ERROR_CODE_x12170000 = The client registration domain ID is null.<br />ERROR_CODE_x12180000 = The client registration computer name is null.<br />ERROR_CODE_x12190000 = The client registration user name is null.<br />ERROR_CODE_x121a0000 = The group path is not invalid.<br />ERROR_CODE_x121b0000 = You have reached the limit of your license.<br />ERROR_CODE_x121c0000 = Failed to create folder for domain.<br />ERROR_CODE_x121d0000 = Failed to create folder for package publish.<br />ERROR_CODE_x121e0000 = The group full name is too long.<br />ERROR_CODE_x121f0000 = The versions of two replication sites do+A321 not match.<br />ERROR_CODE_x12200000 = Invalid database version for logon.<br />ERROR_CODE_x12230000 = Could not log on to the server because of a hostname mismatch. To work around this error, see the Technical Support article for resolving a hostname mismatch (http://www.symantec.com/docs/TECH205165).<br />ERROR_CODE_x12300000 = Console server schema mismatch.<br />ERROR_CODE_x12400000 = Server license info not available.<br />ERROR_CODE_x12500000 = Remote server logon info not available.<br />ERROR_CODE_x12600000 = Remote server license info not available.<br />ERROR_CODE_x12700000 = Remote server schema mismatch.<br />ERROR_CODE_x12800000 = Remote server is not an enterprise server.<br />ERROR_CODE_x12810000 = Remote server system time mismatch.<br />ERROR_CODE_x12900000 = Certificate failed.<br />ERROR_CODE_x12210000 = Failed to download LiveUpdate content.<br />ERROR_CODE_x12220000 = Failed to prepare data.<br />ERROR_CODE_x13010000 = Cannot add root.<br />ERROR_CODE_x13020000 = Cannot delete root.<br />ERROR_CODE_x13160000 = The agent registration data has a null domain name.<br />ERROR_CODE_x13170000 = The agent registration data has a null domain ID.<br />ERROR_CODE_x13180000 = The agent registration data has a null computer name.<br />ERROR_CODE_x13190000 = The agent registration data has a null user name.<br />ERROR_CODE_x14010000 = Authentication failure. Retry.<br />ERROR_CODE_x14020000 = Administrator access denied.<br />ERROR_CODE_x14030000 = Replication access denied.<br />ERROR_CODE_x15010000 = The transaction does not exist.<br />ERROR_CODE_x15020000 = The transaction rollback failed.<br />ERROR_CODE_x15030000 = The transaction commit failed.<br />ERROR_CODE_x15040000 = The transaction start failed.<br />ERROR_CODE_x16010000 = The object cannot be found.<br />ERROR_CODE_x16020000 = The object's content corrupted.<br />ERROR_CODE_x16030000 = The object is concurrently updating.<br />ERROR_CODE_x17010000 = The datastore is not connected.<br />ERROR_CODE_x17020000 = Datastore error.<br />ERROR_CODE_x17030000 = Failed to connect to database.<br />ERROR_CODE_x17040000 = SQL query failed.<br />ERROR_CODE_x18010000 = The target site belongs to a different group of sites.<br />ERROR_CODE_x18020000 = The restore file is invalid.<br />ERROR_CODE_x18030000 = Failed to resolve naming conflict.<br />ERROR_CODE_x19010000 = Email sending failed.<br />ERROR_CODE_x19020000 = Failed to send email directly to mail server.<br />ERROR_CODE_x20010000 = Unsupported SQL Server version.<br />ERROR_CODE_x20020000 = The database task is running.<br />ERROR_CODE_x80010000 = Unexpected console error.<br />ERROR_CODE_x80020000 = Failed to connect to server.<br />ERROR_CODE_x81010000 = Manager response 1 (reserved for future use)<br />ERROR_CODE_x81020000 = Manager response 2 (reserved for future use)<br />ERROR_CODE_x81030000 = Manager response 3 (reserved for future use)<br />ERROR_CODE_x81040000 = Manager response 4 (reserved for future use)<br />ERROR_CODE_x81050000 = Manager response 5 (reserved for future use)<br />ERROR_CODE_x81060000 = Manager administrator log.<br />ERROR_CODE_x81070000 = SQL query submitted.<br />ERROR_CODE_x81080000 = Reset password failed.<br />ERROR_CODE_x82010000 = Administrator is empty.<br />ERROR_CODE_x82020000 = The Java Naming and Directory Interface (JNDI) ignored some data.<br />ERROR_CODE_x83010000 = Administrator name already in use.<br />ERROR_CODE_x83020000 = Top level group cannot be deleted.<br />ERROR_CODE_x83030000 = Cannot delete this group because there are still objects in the group.<br />ERROR_CODE_x83040000 = The domain name is already in use.<br />ERROR_CODE_x83050000 = The Symantec server can only query users from the domains to which it belongs.<br />ERROR_CODE_x83060000 = Domain user query filtered.<br />ERROR_CODE_x83070000 = License error.<br />ERROR_CODE_x84010000 = Invalid password.<br />ERROR_CODE_x84020000 = Invalid password.<br />ERROR_CODE_x84030000 = Invalid password.<br />ERROR_CODE_x84040000 = Invalid password.<br />ERROR_CODE_x84050000 = Invalid password.<br />ERROR_CODE_x84060000 = Invalid password.<br />ERROR_CODE_x84070000 = Invalid certificate file.<br />ERROR_CODE_x84080000 = Invalid certificate file.<br />ERROR_CODE_x84090000 = Failed to write certificate on server.<br />ERROR_CODE_x840a0000 = Invalid keystore.<br />ERROR_CODE_x840b0000 = Invalid private key file.<br />ERROR_CODE_x840c0000 = Invalid certificate file.<br />ERROR_CODE_x840d0000 = Invalid certificate file.<br />ERROR_CODE_x840e0000 = Invalid keystore file.<br />ERROR_CODE_x840f0000 = Invalid key password.<br />ERROR_CODE_x85010000 = The length of an administrator name is invalid.<br />ERROR_CODE_x85020000 = The administrator name contains prohibited characters.<br />ERROR_CODE_x85030000 = The administrator name should not be all dots or spaces.<br />ERROR_CODE_x85040000 = The old and new passwords are the same.<br />ERROR_CODE_x86010000 = An Active Directory node cannot be moved.<br />ERROR_CODE_x86020000 = The global or temporary groups cannot be moved.<br />ERROR_CODE_x86030000 = The group cannot be moved to any Active Directory node.<br />ERROR_CODE_x86040000 = The group cannot be moved to the group Temporary.<br />ERROR_CODE_x86050000 = The destination group is same as the source group.<br />ERROR_CODE_x87010000 = The organization unit is already in use.<br />ERROR_CODE_x88010000 = The host name is empty.<br />ERROR_CODE_x88020000 = Connect directory failed.<br />ERROR_CODE_x89010000 = Failed to read the file.<br />ERROR_CODE_x90010000 = Install issue.<br />ERROR_CODE_x90020000 = Install issue.<br />ERROR_CODE_xA0010000 = The temporary group is not found.<br />ERROR_CODE_xA1010000 = Replication partner not found.<br />ERROR_CODE_xA1020000 = Duplicate names exist.<br />ERROR_CODE_xA1030000 = Failed to check duplicate names.<br />ERROR_CODE_xA2010000 = A site referenced by the system is not found.<br />ERROR_CODE_xA2020000 = The local site seems to have been deleted from the system.<br />ERROR_CODE_xB0010000 = The OU group ID is invalid.<br />ERROR_CODE_xB0020000 = The domain ID is invalid in the session when trying to import OU.<br />ERROR_CODE_xC0010000 = The URL you specified is not accessible. This may be caused by a network connection problem, or the website is down.<br />ERROR_CODE_xD0010000 = No response from the remote server.<br />ERROR_CODE_xE0010000 = The legacy client is not found.<br />ERROR_CODE_xE0050000 = Unknown host name.<br />ERROR_CODE_xE0110000 = The file is not found.<br />ERROR_CODE_xE0120000 = An IO exception occurred.<br />ERROR_CODE_xE0130000 = There is an error when parsing the file.  Check the file format.<br />ERROR_CODE_xE0140000 = A validation error occurred.<br />ERROR_CODE_xE0150000 = Unexpected parameter value.<br />ERROR_CODE_xE0160000 = Invalid parameter.<br />ERROR_CODE_xE0170000 = Missing named version.<br />ERROR_CODE_xE0180000 = Missing PackageLuInfo.<br />ERROR_CODE_xE0190000 = Missing LuCatalog File.<br />ERROR_CODE_xE01A0000 = Missing LuContentPolicy.<br />ERROR_CODE_xE0210000 = Failed to connect to the directory server.<br />ERROR_CODE_xE0220000 = Failed to look up the directory server.<br />ERROR_CODE_xE0230000 = Failed to connect to the specified replication partner server. Verify that the server name and port are correct.<br />ERROR_CODE_XE0240000 = LDAP Authentication failed.<br />ERROR_CODE_xE0310000 = The content that LiveUpdate processed was old.<br />ERROR_CODE_xF0000000 = No client package replication cache.<br />ERROR_CODE_xF00E0000 = No client package content.<br />ERROR_CODE_xF00F0000 = No client package content needed.<br />ERROR_CODE_xF0010000 = Failed to load server list.<br />ERROR_CODE_xF0020000 = Failed to load software package data.<br />ERROR_CODE_xF0030000 = Failed to load binary file.<br />ERROR_CODE_xF0040000 = Failed to unzip file.<br />ERROR_CODE_xF0050000 = Failed to load group profile.<br />ERROR_CODE_xF0060000 = Failed to generate packlist file.<br />ERROR_CODE_xF0070000 = Failed to modify config.xml.<br />ERROR_CODE_xF0080000 = Failed to modify setAid.ini.<br />ERROR_CODE_xF0090000 = Failed to generate single .exe.<br />ERROR_CODE_xF00A0000 = Failed to query database.<br />ERROR_CODE_xF00B0000 = Failed to deploy client package.<br />ERROR_CODE_xF00C0000 = Not enough disk space.<br />ERROR_CODE_xF00D0000 = Failed to copy Host Integrity (HI) Content Library.<br />ERROR_CODE_xF0110000 = Failed to copy license file.<br />ERROR_CODE_xF0120000 = The export folder path is too long. This is probably because the installation path for Symantec Endpoint Protection Manager is too long.<br />ERROR_CODE_xF1000000 = Invalid NST parameters.<br />ERROR_CODE_xF2000000 = NST scan cancelled by user.<br />ERROR_CODE_xF3000000 = NST stopped early because the wait for threads timed out.<br />ERROR_CODE_xF4000000 = NST failed due to missing .dlls.<br />ERROR_CODE_xF5000000 = NST failed due to an unknown error.<br />ERROR_CODE_xF6000000 = NST scan thread timeout.<br />ERROR_CODE_xF7000000 = NST failed for missing auditparams.txt<br />ERROR_CODE_x12910000 = Server certificate not accepted.<br /></td>
</tr>
<tr class='odd'>
 <td class='detail'>STACK_TRACE</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>4000</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The stack trace of the exception (only used when an exception is related to this event).</td>
</tr>
<tr class='even'>
 <td class='detail'>RESERVED_INT1</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>RESERVED_INT2</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='even'>
 <td class='detail'>RESERVED_BIGINT1</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>RESERVED_BIGINT2</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='even'>
 <td class='detail'>RESERVED_CHAR1</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>RESERVED_CHAR2</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='even'>
 <td class='detail'>RESERVED_VARCHAR1</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>520</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>RESERVED_BINARY</td>
 <td class='detail'>varbinary</td>
 <td class='detail' align='right'>2000</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>null</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
</table>
<p title='19 columns'>Analyzed at Wed Apr 12 14:15 PDT 2017<p/>
</td></tr></table>
<div class='indent'>
<b>Indexes:</b>
<table class='dataTable' border='1' rules='groups'><colgroup><colgroup><colgroup><colgroup>
<thead>
 <tr>
  <th>Column(s)</th>
  <th>Type</th>
  <th>Sort</th>
  <th class='constraint' style='text-align:left;'>Constraint Name</th>
 </tr>
</thead>
<tbody>
 <tr>
  <td class='indexedColumn'>USN</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_SERVER_SYSTEM_LOG_1</td>
 </tr>
 <tr>
  <td class='indexedColumn'>SERVER_ID</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_SERVER_SYSTEM_LOG_1_ID_PLUS</td>
 </tr>
 <tr>
  <td class='indexedColumn'>SEVERITY</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_SERVER_SYSTEM_LOG_1_SEV</td>
 </tr>
 <tr>
  <td class='indexedColumn'>TIME_STAMP</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_SERVER_SYSTEM_LOG_1_TIME</td>
 </tr>
 <tr>
  <td class='indexedColumn'>TIME_STAMP + USN + SITE_ID + SERVER_ID + SEVERITY + EVENT_ID</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_SERVER_SYSTEM_LOG_1_TIME_PLUS</td>
 </tr>
</table>
</div>
</div>
</body>
</html>
