<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - Table sem5.dbo.VIRUS</title>
  <link rel=stylesheet href='../schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    table='VIRUS';
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='../index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='../relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='../constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='../anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='../columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>Table <span title='Database'>sem5</span>.<span title='Schema'>dbo</span>.<span title='Table'>VIRUS</span></span><div style='padding: 0px 4px;'>Keeps the list of threats found in the network.</div><p>
</td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%' border='0'>
<tr valign='top'><td class='container' align='left' valign='top'>
<form name='options' action=''>
 <label for='showRelatedCols'><input type=checkbox id='showRelatedCols'>Related columns</label>
 <label for='showConstNames'><input type=checkbox id='showConstNames'>Constraints</label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
 <label for='showLegend'><input type=checkbox checked id='showLegend'>Legend</label>
</form>
</td><td class='container' rowspan='2' align='right' valign='top'>
 <table class='legend' border='0'>
  <tr>
   <td class='dataTable' valign='bottom'>Legend:</td>
  </tr>
  <tr><td class='container' colspan='2'>
   <table class='dataTable' border='1'>
    <tbody>
    <tr><td class='primaryKey'>Primary key columns</td></tr>
    <tr><td class='indexedColumn'>Columns with indexes</td></tr>
    <tr class='impliedRelationship'><td class='detail'><span class='impliedRelationship'>Implied relationships</span></td></tr>
    <tr><td class='excludedColumn'>Excluded column relationships</td></tr>
    <tr><td class='legendDetail'>&lt; <em>n</em> &gt; number of related tables</td></tr>
   </table>
  </td></tr>
 </table>
&nbsp;
</td><tr valign='top'><td class='container' align='left' valign='top'>
<a name='columns'></a>
<table id='columns' class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th>Column</th>
  <th>Type</th>
  <th>Size</th>
  <th title='Are nulls allowed?'>Nulls</th>
  <th title='Is column automatically updated?'>Auto</th>
  <th title='Default value'>Default</th>
  <th title='Columns in tables that reference this column'><span class='notSortedByColumn'>Children</span></th>
  <th title='Columns in tables that are referenced by this column'><span class='notSortedByColumn'>Parents</span></th>
  <th title='Comments' class='comment'><span class='notSortedByColumn'>Comments</span></th>
</tr>
</thead>
<tbody valign='top'>
<tr class='odd'>
 <td class='primaryKey' title='Primary Key'>VIRUSNAME_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>VIRUSNAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Name of virus / threat</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>CATEGORY</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Current category, as downloaded from Symantec's web site. Values are 1 through 5, where 1 is very low and 5 is very severe; -1 means unknown or not applicable. This rating is only applicable to viral threats.</td>
</tr>
<tr class='even'>
 <td class='detail'>MAXCATEGORY</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The maximum category that the virus has reached. Values are 1 through 5, where 1 is very low and 5 is very severe; -1 means unknown or not applicable. This rating is only applicable to viral threats.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>TYPE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Threat type:<br /> 0 = Viral<br /> 1 = Non-viral malicious<br /> 2 = Malicious<br /> 3 = Virus and Spyware - Heuristic<br /> 4 = Security risk<br /> 5 = Hack tool<br /> 6 = Spyware<br /> 7 = Trackware<br /> 8 = Dialer<br /> 9 = Remote access<br /> 10 = Adware<br /> 11 = Jokeware<br /> 12 = Client compliancy<br /> 13 = Generic load point<br /> 14 = Proactive Threat Scan - Heuristic<br /> 15 = Cookie</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>TYPE2</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The threat location:<br /> 0 = Boot virus<br /> 1 = File virus<br /> 2 = Mutation virus<br /> 3 = Macro virus<br /> 4 = File virus<br /> 5 = File virus<br /> 6 = Memory virus<br /> 7 = Memory OS virus<br /> 8 = Memory mcb virus<br /> 9 = Memory highest virus<br /> 11 = Virus behavior<br /> 12 = Virus behavior<br /> 13 = Compressed file<br /> 14 = Heuristic</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>DISCOVERED</td>
 <td class='detail'>datetime</td>
 <td class='detail' align='right'>16,3</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('19700101')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>When the threat was first discovered by Symantec, as downloaded from Symantec's web site.</td>
</tr>
<tr class='even'>
 <td class='detail'>VID</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Unique identifier for a virus, as defined by Security Response.</td>
</tr>
<tr class='odd'>
 <td class='detail'>USN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>A USN-based serial number; this ID is not unique.</td>
</tr>
<tr class='even'>
 <td class='detail'>TIME_STAMP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time on the server when the event is logged into the system (GMT).</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>DELETED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Deleted row: 0 = Not deleted, 1 =  Deleted.</td>
</tr>
<tr class='even'>
 <td class='detail'>PATTERN_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Pointer to the table PATTERN, which protects against this threat/virus.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>TOP_THREAT</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>0 = Not a top threat, 1 = Top threat</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>LATEST_THREAT</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>0 = not a latest threat, 1 = latest threat</td>
</tr>
<tr class='odd'>
 <td class='detail'>STEALTH</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Assesses how easy it is to determine if a security risk is present on a computer. 0 = No rating; 1, 2 = Low; 3 = Medium; 4> = High; -1 means not applicable <br />This rating only applies to non-viral threats.</td>
</tr>
<tr class='even'>
 <td class='detail'>REMOVAL</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The skill level required to remove the threat from a given computer. 0 =  No rating; 1,2 = Low; 3 = Medium; 4 >= = High; -1 means not applicable. This rating only applies to non-viral threats.</td>
</tr>
<tr class='odd'>
 <td class='detail'>PERFORMANCE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Measures the negative impact that the presence of a security risk has on the computer's performance. 0 = No rating, 1, 2 = Low, 3 = Medium, 4>= High; -1 means not applicable. This rating only applies to non-viral threats.</td>
</tr>
<tr class='even'>
 <td class='detail'>PRIVACY</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The level of privacy that is lost due to the presence of a security risk on a computer. 0 = No rating; 1, 2 = Low; 3 = Medium; 4 >= High; -1 means not applicable. This rating only applies to non-viral threats.</td>
</tr>
<tr class='odd'>
 <td class='detail'>DEPENDENCY</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The number of dependent components that the risk installs.  0 = No rating, 1, 2 = Low, 3 = Medium, 4 >= High, -1 means not applicable. This rating only applies to non-viral threats.</td>
</tr>
<tr class='even'>
 <td class='detail'>OVERALL</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>An average of all the security risk ratings. This rating only applies to non-viral threats.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>DYNAUBER</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The uber-category for the risk threat. Links to VIRUSCATEGORY table.</td>
</tr>
<tr class='even'>
 <td class='detail'>DYNACAT</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>(NULL)</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>A sub-category ID for the risk threat. Links to VIRUSCATEGORY table.</td>
</tr>
<tr class='odd'>
 <td class='detail'>DETECTION_TYPE</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((-1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The detection type.</td>
</tr>
</table>
<p title='23 columns'>Analyzed at Wed Apr 12 14:15 PDT 2017<p/>
</td></tr></table>
<div class='indent'>
<b>Indexes:</b>
<table class='dataTable' border='1' rules='groups'><colgroup><colgroup><colgroup><colgroup>
<thead>
 <tr>
  <th>Column(s)</th>
  <th>Type</th>
  <th>Sort</th>
  <th class='constraint' style='text-align:left;'>Constraint Name</th>
 </tr>
</thead>
<tbody>
 <tr>
  <td class='primaryKey'>VIRUSNAME_IDX</td>
  <td class='detail'>Primary key</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>PK_VIRUS</td>
 </tr>
 <tr>
  <td class='indexedColumn'>VIRUSNAME_IDX + VIRUSNAME + CATEGORY + TYPE2 + TYPE + DISCOVERED</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_VIRUS_IDX_PLUS</td>
 </tr>
 <tr>
  <td class='indexedColumn'>LATEST_THREAT + VIRUSNAME</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_VIRUS_LATEST_THREAT_PLUS</td>
 </tr>
 <tr>
  <td class='indexedColumn'>TOP_THREAT + VIRUSNAME</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_VIRUS_TOP_THREAT_PLUS</td>
 </tr>
 <tr>
  <td class='indexedColumn'>VIRUSNAME + DELETED</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_VIRUS_VIRUSNAME_DELETED</td>
 </tr>
 <tr>
  <td class='indexedColumn'>VIRUSNAME_IDX + DYNAUBER + VIRUSNAME + CATEGORY + TYPE2 + DISCOVERED</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_VIRUS_VIRUSNAME_PLUS</td>
 </tr>
</table>
</div>
</div>
</body>
</html>
