<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - Table sem5.dbo.HISTORYCONFIG</title>
  <link rel=stylesheet href='../schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    table='HISTORYCONFIG';
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='../index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='../relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='../constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='../anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='../columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>Table <span title='Database'>sem5</span>.<span title='Schema'>dbo</span>.<span title='Table'>HISTORYCONFIG</span></span><div style='padding: 0px 4px;'>Keeps scheduled report configuration information</div><p>
</td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%' border='0'>
<tr valign='top'><td class='container' align='left' valign='top'>
<form name='options' action=''>
 <label for='showRelatedCols'><input type=checkbox id='showRelatedCols'>Related columns</label>
 <label for='showConstNames'><input type=checkbox id='showConstNames'>Constraints</label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
 <label for='showLegend'><input type=checkbox checked id='showLegend'>Legend</label>
</form>
</td><td class='container' rowspan='2' align='right' valign='top'>
 <table class='legend' border='0'>
  <tr>
   <td class='dataTable' valign='bottom'>Legend:</td>
  </tr>
  <tr><td class='container' colspan='2'>
   <table class='dataTable' border='1'>
    <tbody>
    <tr><td class='primaryKey'>Primary key columns</td></tr>
    <tr><td class='indexedColumn'>Columns with indexes</td></tr>
    <tr class='impliedRelationship'><td class='detail'><span class='impliedRelationship'>Implied relationships</span></td></tr>
    <tr><td class='excludedColumn'>Excluded column relationships</td></tr>
    <tr><td class='legendDetail'>&lt; <em>n</em> &gt; number of related tables</td></tr>
   </table>
  </td></tr>
 </table>
&nbsp;
</td><tr valign='top'><td class='container' align='left' valign='top'>
<a name='columns'></a>
<table id='columns' class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th>Column</th>
  <th>Type</th>
  <th>Size</th>
  <th title='Are nulls allowed?'>Nulls</th>
  <th title='Is column automatically updated?'>Auto</th>
  <th title='Default value'>Default</th>
  <th title='Columns in tables that reference this column'><span class='notSortedByColumn'>Children</span></th>
  <th title='Columns in tables that are referenced by this column'><span class='notSortedByColumn'>Parents</span></th>
  <th title='Comments' class='comment'><span class='notSortedByColumn'>Comments</span></th>
</tr>
</thead>
<tbody valign='top'>
<tr class='even'>
 <td class='primaryKey' title='Primary Key'>HISTORYCONFIG_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>USER_ID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The GUID of the user who created the scheduled report.</td>
</tr>
<tr class='even'>
 <td class='detail'>TZ_OFFSET</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time zone offset from when the administrator created the scheduled report, so that the data is formatted for the administrator's local time zone.</td>
</tr>
<tr class='odd'>
 <td class='detail'>FILTERNAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('Default')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The filter used by the scheduled report.</td>
</tr>
<tr class='even'>
 <td class='detail'>REPORT_IDX</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>10</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('I-0')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Format is Reporttype-number: example I-0 is Virus Definitions Distribution<br /><br />I = Computer Status Report<br />0 = Virus Definitions Distribution<br />1 = Computers Not Checked Into Server<br />2 = Symantec Endpoint Protection Product Versions<br />3 = Intrusion Prevention Signature Distribution<br />4 = Client Inventory<br />5 = Compliance Status Distribution<br />6 = Client Online Status<br />7 = Clients With Latest Policy<br />8 = Client Count by Group<br />9 = Security Status Summary<br />10 = Protection Content Versions<br />11 =Client Migration<br />100 = Client Software Rollout (Snapshots)<br />101 = Clients Online/Offline Over Time (Snapshots)<br />102 = Clients With Latest Policy Over Time (Snapshots)<br />103 = Non-Compliant Clients Over Time (Snapshots)<br />104 = Virus Definition Rollout (Snapshots)<br /><br />A = Audit Report<br />0 = Policies Used<br /><br />B = Application and Device Control Report<br />0 = Top Groups With Most Alerted Application Control Logs<br />1 = Top Targets Blocked<br />2 = Top Devices Blocked<br /><br /><br />C = Compliance Report<br />0 = Network Compliance Status<br />1 = Compliance Status<br />2 = Clients by Compliance Failure Summary<br />3 = Compliance Failure Details<br />4 = Non-compliant Clients by Location<br /><br />F = Network Threat Protection Report<br />0 = Top Targets Attacked<br />1 = Top Sources of Attack<br />2 = Top Types of Attack<br />3 = Top Blocked Applications<br />4 = Attacks Over Time<br />5 = Security Events by Severity<br />6 = Blocked Applications Over Time<br />7 = Traffic Notifications Over Time<br />8 = Top Traffic Notifications<br />9 = Full Report<br /><br />R = Risk Report<br />0  = Infected and At Risk Computers<br />1 = Detection Action Summary<br />2 = Risk Detections Count<br />3 = New Risks Detected in the Network<br />4 = Top Risk Detections Correlation<br />5 = Risk Distribution Summary<br />6 = Risk Distribution Over Time<br />8 = Proactive Threat Detection Results<br />9 = Proactive Threat Distribution<br />10 = Proactive Threat Detection Over Time<br />11 = Action Summary for Top Risks<br />12 = Number of Notifications<br />14 = Number of Notifications Over Time<br />13 = Weekly Outbreaks<br />7 = Comprehensive Risk Report<br /><br />S = Scan Report<br />0 = Scan Statistics Histogram<br />1 = Computers by Last Scan Time<br />2 = Computers Not Scanned<br /><br />Y = System Report<br />0 = Top Clients That Generate Errors<br />1 = Top Servers That Generate Errors<br />2 = Top Enforcers That Generate Errors<br />3 = Database Replication Failures Over Time<br />4 =Site Status Report</td>
</tr>
<tr class='odd'>
 <td class='detail'>STARTTIME</td>
 <td class='detail'>datetime</td>
 <td class='detail' align='right'>16,3</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('19700101')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>When to start generating the report. This establishes its scheduled time within the repeat schedule.</td>
</tr>
<tr class='even'>
 <td class='detail'>LASTRUN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The last time that the report was generated (in GMT).</td>
</tr>
<tr class='odd'>
 <td class='detail'>RUNHOURS</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((24))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Repeat the schedule for this report:<br />1 = Every 1 hour<br />24 = Every 1 day<br />168 = Every week<br />720 = Every month</td>
</tr>
<tr class='even'>
 <td class='detail'>NAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The name of the scheduled report.</td>
</tr>
<tr class='odd'>
 <td class='detail'>EMAIL</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The comma-separated list of email addresses to which the report is sent.</td>
</tr>
<tr class='even'>
 <td class='detail'>DESCRIPTION</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>510</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The administrator-provided description for the report.</td>
</tr>
<tr class='odd'>
 <td class='detail'>DISABLED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Scheduled report disabled: 0 = No, 1 = Yes</td>
</tr>
<tr class='even'>
 <td class='detail'>USN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>A USN-based serial number; this ID is not unique.</td>
</tr>
<tr class='odd'>
 <td class='detail'>TIME_STAMP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time on the server when the event is logged into the system (GMT).</td>
</tr>
<tr class='even'>
 <td class='detail'>DELETED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Deleted row: 0 = Not deleted, 1 = Deleted.</td>
</tr>
<tr class='odd'>
 <td class='detail'>IS_MAIL_TO_SYS_ADMIN</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('1')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The flag for mailing to be sent to system administrator.</td>
</tr>
<tr class='even'>
 <td class='detail'>FILTER_USER_ID</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center' title='nullable'>&nbsp;&radic;&nbsp;</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Filter user ID</td>
</tr>
<tr class='odd'>
 <td class='detail'>TZ_NAME</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>255</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The name of the time zone in which the administrator created the notification, so that emailed reports can display dates in the administrator's local time zone.</td>
</tr>
<tr class='even'>
 <td class='detail'>NEXT_STARTTIME</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='detail'>PREV_RUNHOURS</td>
 <td class='detail'>int</td>
 <td class='detail' align='right'>4</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
</table>
<p title='20 columns'>Analyzed at Wed Apr 12 14:15 PDT 2017<p/>
</td></tr></table>
<div class='indent'>
<b>Indexes:</b>
<table class='dataTable' border='1' rules='groups'><colgroup><colgroup><colgroup><colgroup>
<thead>
 <tr>
  <th>Column(s)</th>
  <th>Type</th>
  <th>Sort</th>
  <th class='constraint' style='text-align:left;'>Constraint Name</th>
 </tr>
</thead>
<tbody>
 <tr>
  <td class='primaryKey'>HISTORYCONFIG_IDX</td>
  <td class='detail'>Primary key</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>PK_HISTORYCONFIG</td>
 </tr>
</table>
</div>
</div>
</body>
</html>
