<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - Table sem5.dbo.SEM_COMPLIANCE_CRITERIA_2</title>
  <link rel=stylesheet href='../schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='../schemaSpy.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>
    table='SEM_COMPLIANCE_CRITERIA_2';
  </SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='../index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='../relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='../constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li><a href='../anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='../columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>Table <span title='Database'>sem5</span>.<span title='Schema'>dbo</span>.<span title='Table'>SEM_COMPLIANCE_CRITERIA_2</span></span><div style='padding: 0px 4px;'>Keeps the host compliance event details.</div><p>
</td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%' border='0'>
<tr valign='top'><td class='container' align='left' valign='top'>
<form name='options' action=''>
 <label for='showRelatedCols'><input type=checkbox id='showRelatedCols'>Related columns</label>
 <label for='showConstNames'><input type=checkbox id='showConstNames'>Constraints</label>
 <label for='showComments'><input type=checkbox checked id='showComments'>Comments</label>
 <label for='showLegend'><input type=checkbox checked id='showLegend'>Legend</label>
</form>
</td><td class='container' rowspan='2' align='right' valign='top'>
 <table class='legend' border='0'>
  <tr>
   <td class='dataTable' valign='bottom'>Legend:</td>
  </tr>
  <tr><td class='container' colspan='2'>
   <table class='dataTable' border='1'>
    <tbody>
    <tr><td class='primaryKey'>Primary key columns</td></tr>
    <tr><td class='indexedColumn'>Columns with indexes</td></tr>
    <tr class='impliedRelationship'><td class='detail'><span class='impliedRelationship'>Implied relationships</span></td></tr>
    <tr><td class='excludedColumn'>Excluded column relationships</td></tr>
    <tr><td class='legendDetail'>&lt; <em>n</em> &gt; number of related tables</td></tr>
   </table>
  </td></tr>
 </table>
&nbsp;
</td><tr valign='top'><td class='container' align='left' valign='top'>
<a name='columns'></a>
<table id='columns' class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup>
<colgroup class='comment'>
<thead align='left'>
<tr>
  <th>Column</th>
  <th>Type</th>
  <th>Size</th>
  <th title='Are nulls allowed?'>Nulls</th>
  <th title='Is column automatically updated?'>Auto</th>
  <th title='Default value'>Default</th>
  <th title='Columns in tables that reference this column'><span class='notSortedByColumn'>Children</span></th>
  <th title='Columns in tables that are referenced by this column'><span class='notSortedByColumn'>Parents</span></th>
  <th title='Comments' class='comment'><span class='notSortedByColumn'>Comments</span></th>
</tr>
</thead>
<tbody valign='top'>
<tr class='even'>
 <td class='primaryKey' title='Primary Key'>CRITERIA_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'></td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>AGENT_SECURITY_LOG_IDX</td>
 <td class='detail'>char</td>
 <td class='detail' align='right'>32</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail'></td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The foreign key to V_AGENT_SECURITY.AGENT_SECURITY_LOG_IDX.</td>
</tr>
<tr class='even'>
 <td class='detail'>ACTION</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>64</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The action, a hard-coded English key, which is one of the following:<br /> Check <br /> Remediation</td>
</tr>
<tr class='odd'>
 <td class='detail'>RULE_NAME</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>512</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The administrator-provided rule name from the policy.</td>
</tr>
<tr class='even'>
 <td class='detail'>RULE_TYPE</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>64</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The hard-coded English key for the type of rule. This key is one of the following: <br />     Antivirus<br />     Antispyware<br />     Patch<br />     Service pack<br />     Firewall<br />     Custom<br />     Unknown - fallback when processing log at the server and action ends up null or blank.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>CRITERIA</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>256</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The hard-coded English key for compliance criteria. Criteria is one of the following:<br />     as_is_installed = Check that antispyware is installed.<br />     as_is_running = Antispyware is running.<br />     as_signature_ok = Antispyware signatures.<br />     av_is_installed = Antispyware is installed.<br />     av_is_running = Antivirus is running.<br />     av_signature_ok = Antivirus signatures.<br />     file_age_ok = Antivirus signature file age.<br />     file_date_ok = The file date.<br />     file_size_ok = The file size.<br />     file_version_ok = The file version.<br />     file_download = The file has downloaded.<br />     file_exists = The file exists.<br />     file_checksum_ok = The file checksum.<br />     file_execute = CThe file command executed.<br />     fw_is_installed = A firewall is installed.<br />     fw_is_running = A firewall is running.<br />     patch_is_installed = A patch is installed.<br />     reg_value_incr = A registry key DWORD has incremented.<br />     reg_key_exists = A registry key exists. <br />     reg_value_ok = A registry value is OK. <br />     reg_value_exists = A registry value exists.<br />     reg_value_set = A registry value is set. <br />     timestamp_ok = A timestamp.<br />     msg_dlg_ok = Aa message dialog returns true.<br />     os_ok = An operating system. <br />     os_lang_ok = An operating system language.<br />     process_is_running = A process is running (either a user app or a service).<br />     file_delete = A temporary file deletes after execution completes or terminates. <br />     service_pack_ok = A service pack meets specific criteria.<br />     hi_setup = Host Integrity setup. <br />     remediation = Provides the overall status of the remediation.<br />     Unknown = The server's default if the criteria is null or blank.</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>TARGET</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>512</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The target of the criteria, which for example could be the antivirus product name, the firewall product name, the file name, the registry key, the registry value, the patch version, the OS version, the process name, or the service name.</td>
</tr>
<tr class='odd'>
 <td class='indexedColumn' title='Indexed'>RESULT</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>64</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The result, which is one of the following:<br />     Pass<br />     Fail<br />     Ignore<br />     Error<br />     Postponed (for remediation criteria only)<br />     Unknown (fallback at the server if the criteria or rule ends up without a final status)<br /></td>
</tr>
<tr class='even'>
 <td class='detail'>ERROR</td>
 <td class='detail'>varchar</td>
 <td class='detail' align='right'>128</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The error, which is one of the following:<br />     unknown = Unknown.<br />     product_unknown = The product is unknown.<br />     file_notfound = The file was not found.<br />     filename_invalid = Invalid file name.<br />     parameter_invalid = The condition parameter is invalid.<br />     parameter_undefined = The policy did not specify the condition parameter.<br />     bad_url = The URL format is invalid.<br />     filedownload_op_err = The URL not is accessible or failed to create the destination file.<br />     time_out = The action timed out.<br />     connection_lost = The connection was lost.<br />     access_violation = There was an access violation on the file.<br />     access_denied = Access was denied.<br />     remediation_abort = The user aborted the remediation.<br />     remediation_postpone = The user postponed the remediation.<br />     createdir_failed = The directory creation failed.<br />     system_err = System error.<br />     runas_noprivilege = The client does not hold a required privilege.<br />     internal_err = Internal error.<br />     os_unknown = Failed to detect the operating system type.</td>
</tr>
<tr class='odd'>
 <td class='detail'>DESCRIPTION</td>
 <td class='detail'>nvarchar</td>
 <td class='detail' align='right'>512</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>('')</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Additional compliance check details. Details are either exception text, or one of the following:<br />      Checksum_blank = The fingerprint value is empty.<br />      Failed_to_get_modification_date = Failed to get the modification date.<br />      NAN = The value is not a number.<br />      Cannot_parse_URL = Cannot parse the URL.<br />      URL_not_accessible_or_failed_to_create_destination_file = The URL is not accessible, or failed to create the destination file.<br />      Download_exceeded_limit = The download exceeded the limit.<br />      Destination = The destination file encountered an access violation.<br />      By_User = The action was initiated by the user.<br />      Access_denied_by_server = Access was denied by the server.<br />      Download_file = The file to download was not found<br />      Process_time_out = The process timed out.<br />      Failed_to_detect_OS_type = Failed to detect OS type.<br />      Application_name_is_empty = The application name is empty.<br />      Probably_software_is_not_installed = The software is probably not installed.<br />      Signature_age_in_seconds_failed = Could not compute the signature's age.<br />      Failed_to_parse_URL = Failed to parse the URL<br />      Missing_or_no_version_info = Missing or no version information.<br />      After_script_file_running = After script file is running.<br />      OS_ignore = The operating system check was ignored.<br />      Save_failed = The save failed.<br />      No_previous_time = No previous time given.<br />      OK_or_YES = The user's response was OK or Yes.<br />      Cancel_or_NO = The user's response was Cancel or No.<br />      Fail_to_get_current_OS_language_version = Could not retrieve the current operating system's language.</td>
</tr>
<tr class='even'>
 <td class='detail'>USN</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((1))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>Update Serial Number; used by replication.</td>
</tr>
<tr class='odd'>
 <td class='detail'>TIME_STAMP</td>
 <td class='detail'>bigint</td>
 <td class='detail' align='right'>8</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The time that the record was modified; used to resolve merge conflict.</td>
</tr>
<tr class='even'>
 <td class='indexedColumn' title='Indexed'>DELETED</td>
 <td class='detail'>tinyint</td>
 <td class='detail' align='right'>1</td>
 <td class='detail' align='center'></td>
 <td class='detail' align='center'></td>
 <td class='detail' align='right'>((0))</td>
 <td class='detail'></td>
 <td class='detail'> </td>
 <td class='comment detail'>The deleted flag of the schema object:<br />1 = Deleted<br />0 = Not deleted</td>
</tr>
</table>
<p title='13 columns'>Analyzed at Wed Apr 12 14:15 PDT 2017<p/>
</td></tr></table>
<div class='indent'>
<b>Indexes:</b>
<table class='dataTable' border='1' rules='groups'><colgroup><colgroup><colgroup><colgroup>
<thead>
 <tr>
  <th>Column(s)</th>
  <th>Type</th>
  <th>Sort</th>
  <th class='constraint' style='text-align:left;'>Constraint Name</th>
 </tr>
</thead>
<tbody>
 <tr>
  <td class='primaryKey'>CRITERIA_IDX</td>
  <td class='detail'>Primary key</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>PK_SEM_COMPLIANCE_CRITERIA_2</td>
 </tr>
 <tr>
  <td class='indexedColumn'>AGENT_SECURITY_LOG_IDX + DELETED + CRITERIA + TARGET + RESULT</td>
  <td class='detail'>Performance</td>
  <td class='detail' style='text-align:left;'><span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span>/<span title='Ascending'>Asc</span></td>
  <td class='constraint' style='text-align:left;'>I_SEM_COMPLIANCE_2_LOG_IDX_PLUS</td>
 </tr>
</table>
</div>
</div>
</body>
</html>
