<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
  <!-- SchemaSpy rev 590 -->
  <title>SchemaSpy - sem5.dbo - Anomalies</title>
  <link rel=stylesheet href='schemaSpy.css' type='text/css'>
  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='jquery.js'></SCRIPT>
  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='schemaSpy.js'></SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
  <li><a href='index.html' title='All tables and views in the schema'>Tables</a></li>
  <li><a href='relationships.html' title='Diagram of table relationships'>Relationships</a></li>
  <li><a href='constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li id='current'><a href='anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li><a href='columns.byTable.html' title="All of the columns in the schema">Columns</a></li>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td></tr></table>
<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
 <tr>
  <td class='heading' valign='middle'><span class='header'>SchemaSpy Analysis of <span title='Database'>sem5</span>.<span title='Schema'>dbo</span> - Anomalies</span><span class='description'>Symantec Endpoint Protection Manager Database Schema</span></td>
  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>
<table width='100%'>
<tr>
<td class='container'><b>Things that might not be 'quite right' about your schema:</b></td>
<td class='container' align='right'>
</td></tr></table>
<ul>
<li>
<b>Columns whose name and type imply a relationship to another table's primary key:</b>
<br>Anomaly not detected<p></li>
<li>
<b>Tables without indexes:</b>
<table class='dataTable' border='1' rules='groups'>
<colgroup>
<thead align='left'>
<tr>
  <th>Table</th>
</tr>
</thead>
<tbody>
 <tr>
  <td class='detail'><a href='tables/CONNECTION_TEST.html'>CONNECTION_TEST</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/DATE_DIMENSION.html'>DATE_DIMENSION</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/DUMMY.html'>DUMMY</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/ENUM_MAP.html'>ENUM_MAP</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/GROUP_LAN_SENSOR.html'>GROUP_LAN_SENSOR</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/HYPERVISOR_PATTERN.html'>HYPERVISOR_PATTERN</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/INVENTORYCURRENTRISK.html'>INVENTORYCURRENTRISK</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/INVENTORYCURRENTVIRUS.html'>INVENTORYCURRENTVIRUS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/NETWORK_SCAN.html'>NETWORK_SCAN</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/NETWORK_SCAN_RESULT.html'>NETWORK_SCAN_RESULT</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SE_GLOBAL.html'>SE_GLOBAL</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_REPLICATION_STATE.html'>SEM_REPLICATION_STATE</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/TASKSTATE.html'>TASKSTATE</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/TIME_OF_DAY.html'>TIME_OF_DAY</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/UPGRADE_CONTENT_LOOKUP.html'>UPGRADE_CONTENT_LOOKUP</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_BEHAVIOR_LOG.html'>V_AGENT_BEHAVIOR_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_PACKET_LOG.html'>V_AGENT_PACKET_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_SECURITY_LOG.html'>V_AGENT_SECURITY_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_SYSTEM_LOG.html'>V_AGENT_SYSTEM_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_TRAFFIC_LOG.html'>V_AGENT_TRAFFIC_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_ALERTS.html'>V_ALERTS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_CLIENT_CHANGE_LOG.html'>V_CLIENT_CHANGE_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_DOMAINS.html'>V_DOMAINS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_ENFORCER_CLIENT_LOG.html'>V_ENFORCER_CLIENT_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_ENFORCER_SYSTEM_LOG.html'>V_ENFORCER_SYSTEM_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_ENFORCER_TRAFFIC_LOG.html'>V_ENFORCER_TRAFFIC_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_GROUPS.html'>V_GROUPS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_IPS.html'>V_IPS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_LAN_DEVICE_DETECTED.html'>V_LAN_DEVICE_DETECTED</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_LAN_DEVICE_EXCLUDED.html'>V_LAN_DEVICE_EXCLUDED</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_MR_CLEAN.html'>V_MR_CLEAN</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_NETWORK_SCAN_RESULT.html'>V_NETWORK_SCAN_RESULT</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SECURITY_VIEW.html'>V_SECURITY_VIEW</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SEM_COMPUTER.html'>V_SEM_COMPUTER</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SEM_CONTENT.html'>V_SEM_CONTENT</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_ADMIN_LOG.html'>V_SERVER_ADMIN_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_CLIENT_LOG.html'>V_SERVER_CLIENT_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_ENFORCER_LOG.html'>V_SERVER_ENFORCER_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_POLICY_LOG.html'>V_SERVER_POLICY_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_SYSTEM_LOG.html'>V_SERVER_SYSTEM_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVERS.html'>V_SERVERS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SONAR.html'>V_SONAR</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_VIRUS.html'>V_VIRUS</a></td>
 </tr>
</tbody>
</table>
43 instances of anomaly detected<p></li>
<li>
<b>Columns that are flagged as both 'nullable' and 'must be unique':</b>
<br>Anomaly not detected<p></li>
<li>
<b>Tables that contain a single column:</b><table class='dataTable' border='1' rules='groups'>
<colgroup>
<colgroup>
<thead align='left'>
<tr>
  <th>Table</th>
  <th>Column</th>
</tr>
</thead>
<tbody>
 <tr>
  <td class='detail'><a href='tables/CONNECTION_TEST.html'>CONNECTION_TEST</a></td><td class='detail'>STATUS</td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SE_GLOBAL.html'>SE_GLOBAL</a></td><td class='detail'>SEQ_NUM</td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/TIME_OF_DAY.html'>TIME_OF_DAY</a></td><td class='detail'>HOUR_ID</td>
 </tr>
</tbody>
</table>
3 instances of anomaly detected<p></li>
<li>
<b>Tables with incrementing column names, potentially indicating denormalization:</b>
<table class='dataTable' border='1' rules='groups'>
<thead align='left'>
<tr>
  <th>Table</th>
</tr>
</thead>
<tbody>
 <tr>
  <td class='detail'><a href='tables/AGENT_BEHAVIOR_LOG_1.html'>AGENT_BEHAVIOR_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_BEHAVIOR_LOG_2.html'>AGENT_BEHAVIOR_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_PACKET_LOG_1.html'>AGENT_PACKET_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_PACKET_LOG_2.html'>AGENT_PACKET_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_SECURITY_LOG_1.html'>AGENT_SECURITY_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_SECURITY_LOG_2.html'>AGENT_SECURITY_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_SYSTEM_LOG_1.html'>AGENT_SYSTEM_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_SYSTEM_LOG_2.html'>AGENT_SYSTEM_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_TRAFFIC_LOG_1.html'>AGENT_TRAFFIC_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/AGENT_TRAFFIC_LOG_2.html'>AGENT_TRAFFIC_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/BASIC_METADATA.html'>BASIC_METADATA</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/BINARY_FILE.html'>BINARY_FILE</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/COMMAND.html'>COMMAND</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/COMPUTER_APPLICATION.html'>COMPUTER_APPLICATION</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/ENFORCER_CLIENT_LOG_1.html'>ENFORCER_CLIENT_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/ENFORCER_CLIENT_LOG_2.html'>ENFORCER_CLIENT_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/ENFORCER_SYSTEM_LOG_1.html'>ENFORCER_SYSTEM_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/ENFORCER_SYSTEM_LOG_2.html'>ENFORCER_SYSTEM_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/ENFORCER_TRAFFIC_LOG_1.html'>ENFORCER_TRAFFIC_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/ENFORCER_TRAFFIC_LOG_2.html'>ENFORCER_TRAFFIC_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/IDENTITY_MAP.html'>IDENTITY_MAP</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/LAN_DEVICE_DETECTED.html'>LAN_DEVICE_DETECTED</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/LAN_DEVICE_EXCLUDED.html'>LAN_DEVICE_EXCLUDED</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/LEGACY_AGENT.html'>LEGACY_AGENT</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/LOCAL_METADATA.html'>LOCAL_METADATA</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/LOG_CONFIG.html'>LOG_CONFIG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/REPORTS.html'>REPORTS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SCANS.html'>SCANS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_AGENT.html'>SEM_AGENT</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_APPLICATION.html'>SEM_APPLICATION</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_CLIENT.html'>SEM_CLIENT</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_COMPUTER.html'>SEM_COMPUTER</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_JOB.html'>SEM_JOB</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_SVA.html'>SEM_SVA</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_SVA_CLIENT.html'>SEM_SVA_CLIENT</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SEM_SVA_COMPUTER.html'>SEM_SVA_COMPUTER</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_ADMIN_LOG_1.html'>SERVER_ADMIN_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_ADMIN_LOG_2.html'>SERVER_ADMIN_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_CLIENT_LOG_1.html'>SERVER_CLIENT_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_CLIENT_LOG_2.html'>SERVER_CLIENT_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_ENFORCER_LOG_1.html'>SERVER_ENFORCER_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_ENFORCER_LOG_2.html'>SERVER_ENFORCER_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_POLICY_LOG_1.html'>SERVER_POLICY_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_POLICY_LOG_2.html'>SERVER_POLICY_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_SYSTEM_LOG_1.html'>SERVER_SYSTEM_LOG_1</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SERVER_SYSTEM_LOG_2.html'>SERVER_SYSTEM_LOG_2</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/SYSTEM_STATE.html'>SYSTEM_STATE</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_BEHAVIOR_LOG.html'>V_AGENT_BEHAVIOR_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_PACKET_LOG.html'>V_AGENT_PACKET_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_SECURITY_LOG.html'>V_AGENT_SECURITY_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_SYSTEM_LOG.html'>V_AGENT_SYSTEM_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_AGENT_TRAFFIC_LOG.html'>V_AGENT_TRAFFIC_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_DOMAINS.html'>V_DOMAINS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_ENFORCER_CLIENT_LOG.html'>V_ENFORCER_CLIENT_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_ENFORCER_SYSTEM_LOG.html'>V_ENFORCER_SYSTEM_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_ENFORCER_TRAFFIC_LOG.html'>V_ENFORCER_TRAFFIC_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_GROUPS.html'>V_GROUPS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_LAN_DEVICE_DETECTED.html'>V_LAN_DEVICE_DETECTED</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_LAN_DEVICE_EXCLUDED.html'>V_LAN_DEVICE_EXCLUDED</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SEM_COMPUTER.html'>V_SEM_COMPUTER</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_ADMIN_LOG.html'>V_SERVER_ADMIN_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_CLIENT_LOG.html'>V_SERVER_CLIENT_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_ENFORCER_LOG.html'>V_SERVER_ENFORCER_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_POLICY_LOG.html'>V_SERVER_POLICY_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVER_SYSTEM_LOG.html'>V_SERVER_SYSTEM_LOG</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_SERVERS.html'>V_SERVERS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/V_VIRUS.html'>V_VIRUS</a></td>
 </tr>
 <tr>
  <td class='detail'><a href='tables/VIRUS.html'>VIRUS</a></td>
 </tr>
</tbody>
</table>
68 instances of anomaly detected<p></li>
<li>
<b>Columns whose default value is the word 'NULL' or 'null', but the SQL NULL value may have been intended:</b>
<br>Anomaly not detected<p></li>
</ul>
</div>
</body>
</html>
